--- 
title: "Crime Mapping and Spatial Data Analysis using R"
author: "Juanjo Medina and Reka Solymosi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: maczokni/crime_mapping
description: "Crime Mapping and Spatial Data Analysis using R"
always_allow_html: true
---
# Preamble: how to use this book  {-}

This book aims to provide the reader with an introduction to R as an engine for spatial data visualisation and analysis for those interested in crime analysis and criminology. The book is based in our lab materials for course units we have offered to upper level undergraduate and MA students on criminology interested in crime mapping, as well as in similar material we have used when training crime analysts working for the police or other law enforcement agencies. 

Given the source material, this book is intended to be uses it as a companion text for similar course units in crime mapping, the geography of crime, environmental criminology, or crime analysis. Equally, it can be used by students, practitioners, and academics alike interested in learning more about R and its GIS and spatial analysis capacity. It is not an advanced statistics text, but rather an applied text. Someone "self teaching" R for these purposes will find it helpful and, thus, unlike reference books, it is better to read and practice each chapter in sequence.

Crime mapping and analysis sits at the intersection of geocomputation, data visualisation and cartography, spatial statistics, environmental criminology, and crime analysis. Environmental criminology provides the substantive background. It concerns the analysis of the spatial and geographical distribution of crime.  

This text cannot make justice to each of this bodies of enquiry, professional practice, and literature. We cannot offer a comprehensive and systematic treatment of each of these areas. What we do is provide a, we hope helpful, introduction to R as a way to bring together these specialties and offer adequate references to our readers so that they can deepen their understanding of each of them. 

Although all the examples we use concern the study of crime, there is fairly limited substantive criminology in the text. In fact, and despite the title, the volume could also be used, more generally, as a companion text for courses on social science spatial data analysis for the techniques we cover are quite general.

In the first part of this volume we introduce key concepts for geographic analysis and representation and provide the reader with the basis to visualise spatial crime data. We then introduce a series of tools and techniques that are relevant to study spatial homogeneity and dependence of crime data. A key focus in this section is how to visualise and detect local clusters of crime and repeat victimisation. The final chapters introduce the students models to account for the distribution of crime across space. In terms of spatial data analysis the focus of the book is on spatial point pattern analysis and lattice or area data analysis. Geostatistics have fewer applications in crime analysis and research and, therefore, we do not cover it here.



```{r include=FALSE}
knitr::opts_chunk$set(cache = F)
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
