<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 Appendix B: Regression analysis (a refresher) | Crime Mapping and Spatial Data Analysis using R</title>
  <meta name="description" content="Chapter 15 Appendix B: Regression analysis (a refresher) | Crime Mapping and Spatial Data Analysis using R" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 Appendix B: Regression analysis (a refresher) | Crime Mapping and Spatial Data Analysis using R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Chapter 15 Appendix B: Regression analysis (a refresher) | Crime Mapping and Spatial Data Analysis using R" />
  <meta name="github-repo" content="maczokni/crime_mapping" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Appendix B: Regression analysis (a refresher) | Crime Mapping and Spatial Data Analysis using R" />
  
  <meta name="twitter:description" content="Chapter 15 Appendix B: Regression analysis (a refresher) | Crime Mapping and Spatial Data Analysis using R" />
  

<meta name="author" content="Juanjo Medina and Reka Solymosi" />


<meta name="date" content="2022-09-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="appendix-a-quick-intro-to-r-and-rstudio.html"/>
<link rel="next" href="appendix-c-sourcing-geographical-data-for-crime-analysis.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<script src="libs/htmlwidgets/htmlwidgets.js"></script>
<link href="libs/leaflet/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet/leaflet.js"></script>
<link href="libs/leafletfix/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4/proj4.min.js"></script>
<script src="libs/Proj4Leaflet/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding/leaflet.js"></script>
<script src="libs/leaflet-providers/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin/leaflet-providers-plugin.js"></script>
<script src="libs/burglary_raster_cc_9107d3/data_stars_burglary_raster_cc983ce5.txt"></script>
<script src="libs/joda/joda.js"></script>
<script src="libs/joda/addImageQuery-bindings.js"></script>
<script src="libs/clipboard/setClipboardText.js"></script>
<link href="libs/HomeButton/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton/home-button.js"></script>
<script src="libs/HomeButton/easy-button-src.min.js"></script>
<link href="libs/mapviewCSS/mapview-popup.css" rel="stylesheet" />
<link href="libs/mapviewCSS/mapview.css" rel="stylesheet" />
<script src="libs/Leaflet.Sync/L.Map.Sync.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Crime Mapping and Spatial Data Analysis using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preamble: how to use this book</a></li>
<li class="chapter" data-level="2" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html"><i class="fa fa-check"></i><b>2</b> Producing your first crime map</a>
<ul>
<li class="chapter" data-level="2.1" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#geospatial-perspective-key-terms-and-ideas"><i class="fa fa-check"></i><b>2.2</b> Geospatial Perspective: key terms and ideas</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#place"><i class="fa fa-check"></i><b>2.2.1</b> Place</a></li>
<li class="chapter" data-level="2.2.2" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#attributes"><i class="fa fa-check"></i><b>2.2.2</b> Attributes</a></li>
<li class="chapter" data-level="2.2.3" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#spatial-objects"><i class="fa fa-check"></i><b>2.2.3</b> Spatial objects</a></li>
<li class="chapter" data-level="2.2.4" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#networks"><i class="fa fa-check"></i><b>2.2.4</b> Networks</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#maps-and-their-types"><i class="fa fa-check"></i><b>2.3</b> Maps and their types</a></li>
<li class="chapter" data-level="2.4" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#map-projections-and-geographic-coordinate-systems"><i class="fa fa-check"></i><b>2.4</b> Map projections and geographic coordinate systems</a></li>
<li class="chapter" data-level="2.5" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#key-terms-summary"><i class="fa fa-check"></i><b>2.5</b> Key terms summary</a></li>
<li class="chapter" data-level="2.6" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#getting-started-with-crime-data"><i class="fa fa-check"></i><b>2.6</b> Getting started with crime data</a></li>
<li class="chapter" data-level="2.7" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#from-dataframes-to-spatial-objects"><i class="fa fa-check"></i><b>2.7</b> From dataframes to spatial objects</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#the-point"><i class="fa fa-check"></i><b>2.7.1</b> The point</a></li>
<li class="chapter" data-level="2.7.2" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#the-line"><i class="fa fa-check"></i><b>2.7.2</b> The line</a></li>
<li class="chapter" data-level="2.7.3" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#the-polygon"><i class="fa fa-check"></i><b>2.7.3</b> The polygon</a></li>
<li class="chapter" data-level="2.7.4" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#choosing-the-ideal-unit-of-analysis"><i class="fa fa-check"></i><b>2.7.4</b> Choosing the ideal unit of analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#the-simple-features-framework"><i class="fa fa-check"></i><b>2.8</b> The simple features framework</a></li>
<li class="chapter" data-level="2.9" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#plotting-data-with-ggplot2"><i class="fa fa-check"></i><b>2.9</b> Plotting data with ggplot2</a></li>
<li class="chapter" data-level="2.10" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#mapping-crime-data-as-points"><i class="fa fa-check"></i><b>2.10</b> Mapping crime data as points</a></li>
<li class="chapter" data-level="2.11" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#mapping-crime-data-as-polygons"><i class="fa fa-check"></i><b>2.11</b> Mapping crime data as polygons</a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#finding-boundary-data"><i class="fa fa-check"></i><b>2.11.1</b> Finding boundary data</a></li>
<li class="chapter" data-level="2.11.2" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#reading-shapefiles-into-r"><i class="fa fa-check"></i><b>2.11.2</b> Reading shapefiles into R</a></li>
<li class="chapter" data-level="2.11.3" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.11.3</b> Data wrangling with dplyr</a></li>
<li class="chapter" data-level="2.11.4" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#join-data-to-sf-object"><i class="fa fa-check"></i><b>2.11.4</b> Join data to sf object</a></li>
<li class="chapter" data-level="2.11.5" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#putting-polygon-data-on-the-map"><i class="fa fa-check"></i><b>2.11.5</b> Putting polygon data on the map</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="producing-your-first-crime-map.html"><a href="producing-your-first-crime-map.html#summary-and-further-reading"><i class="fa fa-check"></i><b>2.12</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html"><i class="fa fa-check"></i><b>3</b> Basic geospatial operations in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#exploring-the-relationship-between-alcohol-outlets-and-crime"><i class="fa fa-check"></i><b>3.2</b> Exploring the relationship between alcohol outlets and crime</a></li>
<li class="chapter" data-level="3.3" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#acquiring-relevant-data"><i class="fa fa-check"></i><b>3.3</b> Acquiring relevant data</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#reading-in-crime-data"><i class="fa fa-check"></i><b>3.3.1</b> Reading in crime data</a></li>
<li class="chapter" data-level="3.3.2" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#meet-a-new-format-geojson"><i class="fa fa-check"></i><b>3.3.2</b> Meet a new format: geoJSON</a></li>
<li class="chapter" data-level="3.3.3" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#open-street-map-and-points-of-interest"><i class="fa fa-check"></i><b>3.3.3</b> Open Street Map and points of interest</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#attribute-operations"><i class="fa fa-check"></i><b>3.4</b> Attribute operations</a></li>
<li class="chapter" data-level="3.5" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#spatial-operations"><i class="fa fa-check"></i><b>3.5</b> Spatial operations</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#reprojecting-coordinates"><i class="fa fa-check"></i><b>3.5.1</b> Reprojecting coordinates</a></li>
<li class="chapter" data-level="3.5.2" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#subsetting-points"><i class="fa fa-check"></i><b>3.5.2</b> Subsetting points</a></li>
<li class="chapter" data-level="3.5.3" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#building-buffers"><i class="fa fa-check"></i><b>3.5.3</b> Building buffers</a></li>
<li class="chapter" data-level="3.5.4" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#counting-points-within-a-polygon"><i class="fa fa-check"></i><b>3.5.4</b> Counting Points within a Polygon</a></li>
<li class="chapter" data-level="3.5.5" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#distances-finding-the-nearest-point"><i class="fa fa-check"></i><b>3.5.5</b> Distances: Finding the nearest point</a></li>
<li class="chapter" data-level="3.5.6" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#measuring-distances"><i class="fa fa-check"></i><b>3.5.6</b> Measuring distances</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#plotting-interactive-maps-with-leaflet"><i class="fa fa-check"></i><b>3.6</b> Plotting interactive maps with leaflet</a></li>
<li class="chapter" data-level="3.7" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#geocoding"><i class="fa fa-check"></i><b>3.7</b> Geocoding</a></li>
<li class="chapter" data-level="3.8" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#measuring-distance-more-thoroughly"><i class="fa fa-check"></i><b>3.8</b> Measuring distance more thoroughly</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#how-far-are-police-stations-in-madrid"><i class="fa fa-check"></i><b>3.8.1</b> How far are police stations in Madrid?</a></li>
<li class="chapter" data-level="3.8.2" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#distance-in-geographical-space"><i class="fa fa-check"></i><b>3.8.2</b> Distance in geographical space</a></li>
<li class="chapter" data-level="3.8.3" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#a-practical-example-to-evaluate-distance"><i class="fa fa-check"></i><b>3.8.3</b> A practical example to evaluate distance</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="basic-geospatial-operations-in-r.html"><a href="basic-geospatial-operations-in-r.html#summary-and-further-reading-1"><i class="fa fa-check"></i><b>3.9</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html"><i class="fa fa-check"></i><b>4</b> Mapping rates and counts</a>
<ul>
<li class="chapter" data-level="4.1" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#thematic-maps-key-terms-and-ideas"><i class="fa fa-check"></i><b>4.2</b> Thematic maps: key terms and ideas</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#choropleth-maps"><i class="fa fa-check"></i><b>4.2.1</b> Choropleth maps</a></li>
<li class="chapter" data-level="4.2.2" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#what-do-we-use-choropleth-maps-for"><i class="fa fa-check"></i><b>4.2.2</b> What do we use choropleth maps for?</a></li>
<li class="chapter" data-level="4.2.3" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#proportional-and-graduate-symbol-maps-mapping-crime-counts"><i class="fa fa-check"></i><b>4.2.3</b> Proportional and graduate symbol maps: mapping crime counts</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#creating-proportional-symbol-maps"><i class="fa fa-check"></i><b>4.3</b> Creating proportional symbol maps</a></li>
<li class="chapter" data-level="4.4" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#mapping-rates-rather-than-counts"><i class="fa fa-check"></i><b>4.4</b> Mapping rates rather than counts</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#generating-the-rates"><i class="fa fa-check"></i><b>4.4.1</b> Generating the rates</a></li>
<li class="chapter" data-level="4.4.2" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#creating-a-choropleth-map-with-tmap"><i class="fa fa-check"></i><b>4.4.2</b> Creating a choropleth map with tmap</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#classification-systems-for-thematic-maps"><i class="fa fa-check"></i><b>4.5</b> Classification systems for thematic maps</a></li>
<li class="chapter" data-level="4.6" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#interactive-mapping-with-tmap"><i class="fa fa-check"></i><b>4.6</b> Interactive mapping with tmap</a></li>
<li class="chapter" data-level="4.7" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#smoothing-rates-adjusting-for-small-sample-noise"><i class="fa fa-check"></i><b>4.7</b> Smoothing rates: adjusting for small sample noise</a></li>
<li class="chapter" data-level="4.8" data-path="mapping-rates-and-counts.html"><a href="mapping-rates-and-counts.html#summary-and-further-reading-2"><i class="fa fa-check"></i><b>4.8</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html"><i class="fa fa-check"></i><b>5</b> Variations of thematic mapping</a>
<ul>
<li class="chapter" data-level="5.1" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#binning-points"><i class="fa fa-check"></i><b>5.2</b> Binning points</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#the-binning-process"><i class="fa fa-check"></i><b>5.2.1</b> The Binning Process</a></li>
<li class="chapter" data-level="5.2.2" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#different-binning-techniques"><i class="fa fa-check"></i><b>5.2.2</b> Different Binning Techniques</a></li>
<li class="chapter" data-level="5.2.3" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#benefits-of-binning"><i class="fa fa-check"></i><b>5.2.3</b> Benefits of Binning</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#transforming-polygons-cartograms"><i class="fa fa-check"></i><b>5.3</b> Transforming polygons: cartograms</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#dorling-cartogram"><i class="fa fa-check"></i><b>5.3.1</b> Dorling Cartogram</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#bivariate-maps"><i class="fa fa-check"></i><b>5.4</b> Bivariate Maps</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#step-1-bin-our-variables-of-interest"><i class="fa fa-check"></i><b>5.4.1</b> Step 1: Bin our variables of interest</a></li>
<li class="chapter" data-level="5.4.2" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#step-2-new-variable"><i class="fa fa-check"></i><b>5.4.2</b> Step 2: New variable</a></li>
<li class="chapter" data-level="5.4.3" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#step-3-create-colour-scheme"><i class="fa fa-check"></i><b>5.4.3</b> Step 3: Create colour scheme</a></li>
<li class="chapter" data-level="5.4.4" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#step-4-join-colour-scheme"><i class="fa fa-check"></i><b>5.4.4</b> Step 4: Join colour scheme</a></li>
<li class="chapter" data-level="5.4.5" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#step-5-create-legend"><i class="fa fa-check"></i><b>5.4.5</b> Step 5: Create legend</a></li>
<li class="chapter" data-level="5.4.6" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#step-6-map"><i class="fa fa-check"></i><b>5.4.6</b> Step 6: Map</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#a-note-of-caution-maup"><i class="fa fa-check"></i><b>5.5</b> A note of caution: MAUP</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#why-does-maup-matter"><i class="fa fa-check"></i><b>5.5.1</b> Why does MAUP matter?</a></li>
<li class="chapter" data-level="5.5.2" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#what-can-we-do"><i class="fa fa-check"></i><b>5.5.2</b> What can we do?</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="variations-of-thematic-mapping.html"><a href="variations-of-thematic-mapping.html#summary-and-further-reading-3"><i class="fa fa-check"></i><b>5.6</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html"><i class="fa fa-check"></i><b>6</b> Basics of cartographic design: elements of a map</a>
<ul>
<li class="chapter" data-level="6.1" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#introduction-4"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#data-representation"><i class="fa fa-check"></i><b>6.2</b> Data representation</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#thematic-maps"><i class="fa fa-check"></i><b>6.2.1</b> Thematic maps</a></li>
<li class="chapter" data-level="6.2.2" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#symbols"><i class="fa fa-check"></i><b>6.2.2</b> Symbols</a></li>
<li class="chapter" data-level="6.2.3" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#rate-vs-count"><i class="fa fa-check"></i><b>6.2.3</b> Rate vs count</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#colour"><i class="fa fa-check"></i><b>6.3</b> Colour</a></li>
<li class="chapter" data-level="6.4" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#text"><i class="fa fa-check"></i><b>6.4</b> Text</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#titles-and-subtitles"><i class="fa fa-check"></i><b>6.4.1</b> Titles and subtitles</a></li>
<li class="chapter" data-level="6.4.2" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#legend"><i class="fa fa-check"></i><b>6.4.2</b> Legend</a></li>
<li class="chapter" data-level="6.4.3" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#annotation"><i class="fa fa-check"></i><b>6.4.3</b> Annotation</a></li>
<li class="chapter" data-level="6.4.4" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#production-notes"><i class="fa fa-check"></i><b>6.4.4</b> Production notes</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#composition"><i class="fa fa-check"></i><b>6.5</b> Composition</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#orientation-indicators"><i class="fa fa-check"></i><b>6.5.1</b> Orientation indicators</a></li>
<li class="chapter" data-level="6.5.2" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#scale-indicators"><i class="fa fa-check"></i><b>6.5.2</b> Scale indicators</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#context"><i class="fa fa-check"></i><b>6.6</b> Context</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#basemap"><i class="fa fa-check"></i><b>6.6.1</b> Basemap</a></li>
<li class="chapter" data-level="6.6.2" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#inset-maps"><i class="fa fa-check"></i><b>6.6.2</b> Inset maps</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="basics-of-cartographic-design-elements-of-a-map.html"><a href="basics-of-cartographic-design-elements-of-a-map.html#summary-and-further-reading-4"><i class="fa fa-check"></i><b>6.7</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="time-matters.html"><a href="time-matters.html"><i class="fa fa-check"></i><b>7</b> Time matters</a>
<ul>
<li class="chapter" data-level="7.1" data-path="time-matters.html"><a href="time-matters.html#introduction-5"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="time-matters.html"><a href="time-matters.html#temporal-data-in-crime-analysis"><i class="fa fa-check"></i><b>7.2</b> Temporal data in crime analysis</a></li>
<li class="chapter" data-level="7.3" data-path="time-matters.html"><a href="time-matters.html#temporal-data-wrangling"><i class="fa fa-check"></i><b>7.3</b> Temporal data wrangling</a></li>
<li class="chapter" data-level="7.4" data-path="time-matters.html"><a href="time-matters.html#visualising-time-data"><i class="fa fa-check"></i><b>7.4</b> Visualising time data</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="time-matters.html"><a href="time-matters.html#how-not-to-present-time"><i class="fa fa-check"></i><b>7.4.1</b> How (not) to present time</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="time-matters.html"><a href="time-matters.html#time-series-analysis"><i class="fa fa-check"></i><b>7.5</b> Time series analysis</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="time-matters.html"><a href="time-matters.html#plotting-time-series-data"><i class="fa fa-check"></i><b>7.5.1</b> Plotting time series data</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="time-matters.html"><a href="time-matters.html#spatio-temporal-data-visualisation"><i class="fa fa-check"></i><b>7.6</b> Spatio-temporal data visualisation</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="time-matters.html"><a href="time-matters.html#small-multiples-to-show-temporal-variation"><i class="fa fa-check"></i><b>7.6.1</b> Small multiples to show temporal variation</a></li>
<li class="chapter" data-level="7.6.2" data-path="time-matters.html"><a href="time-matters.html#spaghetti-plots"><i class="fa fa-check"></i><b>7.6.2</b> Spaghetti plots</a></li>
<li class="chapter" data-level="7.6.3" data-path="time-matters.html"><a href="time-matters.html#animations"><i class="fa fa-check"></i><b>7.6.3</b> Animations</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="time-matters.html"><a href="time-matters.html#summary-and-further-reading-5"><i class="fa fa-check"></i><b>7.7</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html"><i class="fa fa-check"></i><b>8</b> Spatial point patterns of crime events</a>
<ul>
<li class="chapter" data-level="8.1" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#mapping-crime-intensity-with-isarithmic-maps"><i class="fa fa-check"></i><b>8.1</b> Mapping crime intensity with isarithmic maps</a></li>
<li class="chapter" data-level="8.2" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#burglaries-in-nyc"><i class="fa fa-check"></i><b>8.2</b> Burglaries in NYC</a></li>
<li class="chapter" data-level="8.3" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#using-the-spatstat-package"><i class="fa fa-check"></i><b>8.3</b> Using the <code>spatstat</code> package</a></li>
<li class="chapter" data-level="8.4" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#homogeneous-or-spatially-varying-intensity"><i class="fa fa-check"></i><b>8.4</b> Homogeneous or spatially varying intensity?</a></li>
<li class="chapter" data-level="8.5" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#mapping-intensity-estimates-with-spatstat"><i class="fa fa-check"></i><b>8.5</b> Mapping intensity estimates with <code>spatstat</code></a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#basics-of-kernel-density-estimation-kde"><i class="fa fa-check"></i><b>8.5.1</b> Basics of kernel density estimation (KDE)</a></li>
<li class="chapter" data-level="8.5.2" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#selecting-the-appropriate-bandwith-for-kde"><i class="fa fa-check"></i><b>8.5.2</b> Selecting the appropriate bandwith for KDE</a></li>
<li class="chapter" data-level="8.5.3" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#selecting-the-smoothing-kernel"><i class="fa fa-check"></i><b>8.5.3</b> Selecting the smoothing kernel</a></li>
<li class="chapter" data-level="8.5.4" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#weighted-kernel-density-estimates"><i class="fa fa-check"></i><b>8.5.4</b> Weighted kernel density estimates</a></li>
<li class="chapter" data-level="8.5.5" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#better-kde-maps-using-leaflet"><i class="fa fa-check"></i><b>8.5.5</b> Better KDE maps using <code>leaflet</code></a></li>
<li class="chapter" data-level="8.5.6" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#problems-with-kde"><i class="fa fa-check"></i><b>8.5.6</b> Problems with KDE</a></li>
<li class="chapter" data-level="8.5.7" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#other-packages-for-kde"><i class="fa fa-check"></i><b>8.5.7</b> Other packages for KDE</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="spatial-point-patterns-of-crime-events.html"><a href="spatial-point-patterns-of-crime-events.html#summary-and-further-reading-6"><i class="fa fa-check"></i><b>8.6</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html"><i class="fa fa-check"></i><b>9</b> Crime along spatial networks</a>
<ul>
<li class="chapter" data-level="9.1" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#introduction-6"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#constructing-and-storing-a-spatial-linear-network"><i class="fa fa-check"></i><b>9.2</b> Constructing and storing a spatial linear network</a></li>
<li class="chapter" data-level="9.3" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#density-estimation-along-networks"><i class="fa fa-check"></i><b>9.3</b> Density estimation along networks</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#adding-context"><i class="fa fa-check"></i><b>9.3.1</b> Adding context</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#visualising-crime-distribution-along-networks"><i class="fa fa-check"></i><b>9.4</b> Visualising crime distribution along networks</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#hot-routes"><i class="fa fa-check"></i><b>9.4.1</b> Hot Routes</a></li>
<li class="chapter" data-level="9.4.2" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#street-profile-analysis"><i class="fa fa-check"></i><b>9.4.2</b> Street Profile Analysis</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#quantifying-crime-concentration-at-micro-places"><i class="fa fa-check"></i><b>9.5</b> Quantifying crime concentration at micro-places</a></li>
<li class="chapter" data-level="9.6" data-path="crime-along-spatial-networks.html"><a href="crime-along-spatial-networks.html#summary-and-further-reading-7"><i class="fa fa-check"></i><b>9.6</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html"><i class="fa fa-check"></i><b>10</b> Spatial dependence and autocorrelation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#introduction-7"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#exploring-spatial-dependence-in-point-pattern-data"><i class="fa fa-check"></i><b>10.2</b> Exploring spatial dependence in point pattern data</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#the-empirical-k-function"><i class="fa fa-check"></i><b>10.2.1</b> The empirical K function</a></li>
<li class="chapter" data-level="10.2.2" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#homicide-in-buenos-aires"><i class="fa fa-check"></i><b>10.2.2</b> Homicide in Buenos Aires</a></li>
<li class="chapter" data-level="10.2.3" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#estimating-and-plotting-the-k-function"><i class="fa fa-check"></i><b>10.2.3</b> Estimating and plotting the K-function</a></li>
<li class="chapter" data-level="10.2.4" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#network-constrained-k-function"><i class="fa fa-check"></i><b>10.2.4</b> Network constrained K function</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#exploring-spatial-autocorrelation-in-lattice-data"><i class="fa fa-check"></i><b>10.3</b> Exploring spatial autocorrelation in lattice data</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#burglary-in-manchester"><i class="fa fa-check"></i><b>10.3.1</b> Burglary in Manchester</a></li>
<li class="chapter" data-level="10.3.2" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#what-is-a-neighbour"><i class="fa fa-check"></i><b>10.3.2</b> What is a neighbour?</a></li>
<li class="chapter" data-level="10.3.3" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#creating-a-list-of-neighbours-based-on-contiguity"><i class="fa fa-check"></i><b>10.3.3</b> Creating a list of neighbours based on contiguity</a></li>
<li class="chapter" data-level="10.3.4" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#generating-the-weight-matrix"><i class="fa fa-check"></i><b>10.3.4</b> Generating the weight matrix</a></li>
<li class="chapter" data-level="10.3.5" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#spatial-weight-matrix-based-on-distance"><i class="fa fa-check"></i><b>10.3.5</b> Spatial weight matrix based on distance</a></li>
<li class="chapter" data-level="10.3.6" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#spatial-weight-matrix-based-on-k-neighbors"><i class="fa fa-check"></i><b>10.3.6</b> Spatial weight matrix based on k-neighbors</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#choosing-the-correct-matrix"><i class="fa fa-check"></i><b>10.4</b> Choosing the correct matrix</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#measuring-global-autocorrelation"><i class="fa fa-check"></i><b>10.4.1</b> Measuring global autocorrelation</a></li>
<li class="chapter" data-level="10.4.2" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#the-rgeoda-and-sfweight-packages"><i class="fa fa-check"></i><b>10.4.2</b> The <code>rgeoda</code> and <code>sfweight</code> packages</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="spatial-dependence-and-autocorrelation.html"><a href="spatial-dependence-and-autocorrelation.html#further-reading"><i class="fa fa-check"></i><b>10.5</b> Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html"><i class="fa fa-check"></i><b>11</b> Detecting hot spots and repeats</a>
<ul>
<li class="chapter" data-level="11.1" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#introduction-8"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#clusters-hot-spots-of-crime-and-near-repeat-victimisation"><i class="fa fa-check"></i><b>11.1.1</b> Clusters, hot spots of crime, and near repeat victimisation</a></li>
<li class="chapter" data-level="11.1.2" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#burglaries-in-manchester"><i class="fa fa-check"></i><b>11.1.2</b> Burglaries in Manchester</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#using-raster-micro-grid-cells-to-spot-hot-spots"><i class="fa fa-check"></i><b>11.2</b> Using <code>raster</code> micro grid cells to spot hot spots</a></li>
<li class="chapter" data-level="11.3" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#local-getis-ord"><i class="fa fa-check"></i><b>11.3</b> Local Getis-Ord</a></li>
<li class="chapter" data-level="11.4" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#local-morans-i-and-moran-scaterplot"><i class="fa fa-check"></i><b>11.4</b> Local Moran’s I and Moran scaterplot</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#computing-the-local-morans-i"><i class="fa fa-check"></i><b>11.4.1</b> Computing the local Moran’s I</a></li>
<li class="chapter" data-level="11.4.2" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#creating-a-lisa-map"><i class="fa fa-check"></i><b>11.4.2</b> Creating a LISA map</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#scan-satistics"><i class="fa fa-check"></i><b>11.5</b> Scan satistics</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#the-dcluster-package"><i class="fa fa-check"></i><b>11.5.1</b> The <code>DCluster</code> package</a></li>
<li class="chapter" data-level="11.5.2" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#openshaws-gam"><i class="fa fa-check"></i><b>11.5.2</b> Openshaw’s GAM</a></li>
<li class="chapter" data-level="11.5.3" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#kulldorfs-scan-statistic"><i class="fa fa-check"></i><b>11.5.3</b> Kulldorf’s Scan Statistic</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#exploring-near-repeat-victimisation"><i class="fa fa-check"></i><b>11.6</b> Exploring near repeat victimisation</a></li>
<li class="chapter" data-level="11.7" data-path="detecting-hot-spots-and-repeats.html"><a href="detecting-hot-spots-and-repeats.html#further-reading-1"><i class="fa fa-check"></i><b>11.7</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html"><i class="fa fa-check"></i><b>12</b> Spatial regression models</a>
<ul>
<li class="chapter" data-level="12.1" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#introduction-9"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#challenges-for-regression-with-spatial-data"><i class="fa fa-check"></i><b>12.2</b> Challenges for regression with spatial data</a></li>
<li class="chapter" data-level="12.3" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#fitting-a-non-spatial-regression-model-with-r"><i class="fa fa-check"></i><b>12.3</b> Fitting a non-spatial regression model with R</a></li>
<li class="chapter" data-level="12.4" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#looking-at-the-residuals-and-testing-for-spatial-autocorrelation-in-regression"><i class="fa fa-check"></i><b>12.4</b> Looking at the residuals and testing for spatial autocorrelation in regression</a></li>
<li class="chapter" data-level="12.5" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i><b>12.5</b> Choosing a spatial regression model</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#the-basic-spatial-models"><i class="fa fa-check"></i><b>12.5.1</b> The basic spatial models</a></li>
<li class="chapter" data-level="12.5.2" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#lagrange-multipliers-the-bottom-up-approach-to-select-a-model"><i class="fa fa-check"></i><b>12.5.2</b> Lagrange multipliers: the bottom-up approach to select a model</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#fitting-and-interpreting-a-spatial-error-model"><i class="fa fa-check"></i><b>12.6</b> Fitting and interpreting a spatial error model</a></li>
<li class="chapter" data-level="12.7" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#fitting-and-interpreting-a-spatially-lagged-model"><i class="fa fa-check"></i><b>12.7</b> Fitting and interpreting a spatially lagged model</a></li>
<li class="chapter" data-level="12.8" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#beyond-the-sar-and-sem-models"><i class="fa fa-check"></i><b>12.8</b> Beyond the SAR and SEM models</a></li>
<li class="chapter" data-level="12.9" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#summary-and-further-reading-8"><i class="fa fa-check"></i><b>12.9</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html"><i class="fa fa-check"></i><b>13</b> Spatial heterogeneity and regression</a>
<ul>
<li class="chapter" data-level="13.1" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#introduction-10"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#spatial-regimes"><i class="fa fa-check"></i><b>13.2</b> Spatial regimes</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#fitting-the-constrained-and-the-unconstrained-models"><i class="fa fa-check"></i><b>13.2.1</b> Fitting the constrained and the unconstrained models</a></li>
<li class="chapter" data-level="13.2.2" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#running-the-chow-test"><i class="fa fa-check"></i><b>13.2.2</b> Running the Chow test</a></li>
<li class="chapter" data-level="13.2.3" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#spatial-dependence-with-spatial-heterogeneity"><i class="fa fa-check"></i><b>13.2.3</b> Spatial dependence with spatial heterogeneity</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#geographically-weighted-regression"><i class="fa fa-check"></i><b>13.3</b> Geographically Weighted Regression</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#calculate-kernel-bandwidth"><i class="fa fa-check"></i><b>13.3.1</b> Calculate kernel bandwidth</a></li>
<li class="chapter" data-level="13.3.2" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#building-the-geographically-weighted-model"><i class="fa fa-check"></i><b>13.3.2</b> Building the geographically weighted model</a></li>
<li class="chapter" data-level="13.3.3" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#using-gwr"><i class="fa fa-check"></i><b>13.3.3</b> Using GWR</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="spatial-heterogeneity-and-regression.html"><a href="spatial-heterogeneity-and-regression.html#summary-and-further-reading-9"><i class="fa fa-check"></i><b>13.4</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>14</b> Appendix: A quick intro to R and RStudio</a>
<ul>
<li class="chapter" data-level="14.1" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#exploring-rstudio"><i class="fa fa-check"></i><b>14.1</b> Exploring RStudio</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#the-four-panes-of-r-studio"><i class="fa fa-check"></i><b>14.1.1</b> The four panes of R Studio</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>14.2</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="14.3" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#elements-of-r-grammar"><i class="fa fa-check"></i><b>14.3</b> Elements of R grammar</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#functions"><i class="fa fa-check"></i><b>14.3.1</b> Functions</a></li>
<li class="chapter" data-level="14.3.2" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#objects"><i class="fa fa-check"></i><b>14.3.2</b> Objects</a></li>
<li class="chapter" data-level="14.3.3" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#types-of-objects"><i class="fa fa-check"></i><b>14.3.3</b> Types of objects</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#packages"><i class="fa fa-check"></i><b>14.4</b> Packages</a></li>
<li class="chapter" data-level="14.5" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#exploring-data-with-r"><i class="fa fa-check"></i><b>14.5</b> Exploring data with R</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#playing-around-with-data"><i class="fa fa-check"></i><b>14.5.1</b> Playing around with data</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>14.6</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="14.7" data-path="appendix-a-quick-intro-to-r-and-rstudio.html"><a href="appendix-a-quick-intro-to-r-and-rstudio.html#summary-and-further-reading-10"><i class="fa fa-check"></i><b>14.7</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html"><i class="fa fa-check"></i><b>15</b> Appendix B: Regression analysis (a refresher)</a>
<ul>
<li class="chapter" data-level="15.1" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#introduction-11"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#motivating-regression"><i class="fa fa-check"></i><b>15.2</b> Motivating regression</a></li>
<li class="chapter" data-level="15.3" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>15.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="15.4" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#residuals-revisited-r-squared"><i class="fa fa-check"></i><b>15.4</b> Residuals revisited: R squared</a></li>
<li class="chapter" data-level="15.5" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#inference-with-regression"><i class="fa fa-check"></i><b>15.5</b> Inference with regression</a></li>
<li class="chapter" data-level="15.6" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>15.6</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="15.7" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>15.7</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="15.8" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>15.8</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="15.9" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#presenting-your-regression-results."><i class="fa fa-check"></i><b>15.9</b> Presenting your regression results.</a></li>
<li class="chapter" data-level="15.10" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#rescaling-input-variables-to-assist-interpretation"><i class="fa fa-check"></i><b>15.10</b> Rescaling input variables to assist interpretation</a></li>
<li class="chapter" data-level="15.11" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>15.11</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="15.12" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#model-building-and-variable-selection"><i class="fa fa-check"></i><b>15.12</b> Model building and variable selection</a></li>
<li class="chapter" data-level="15.13" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#regression-assumptions"><i class="fa fa-check"></i><b>15.13</b> Regression assumptions</a></li>
<li class="chapter" data-level="15.14" data-path="appendix-b-regression-analysis-a-refresher.html"><a href="appendix-b-regression-analysis-a-refresher.html#summary-and-further-reading-11"><i class="fa fa-check"></i><b>15.14</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><i class="fa fa-check"></i><b>16</b> Appendix C: sourcing geographical data for crime analysis</a>
<ul>
<li class="chapter" data-level="16.1" data-path="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html#the-rnaturalearth-package"><i class="fa fa-check"></i><b>16.1</b> The rnaturalearth package</a></li>
<li class="chapter" data-level="16.2" data-path="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html#data-from-apis"><i class="fa fa-check"></i><b>16.2</b> Data from APIs</a></li>
<li class="chapter" data-level="16.3" data-path="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html#data-from-data-repositories"><i class="fa fa-check"></i><b>16.3</b> Data from data repositories</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html#international-resources"><i class="fa fa-check"></i><b>16.3.1</b> International resources</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html#open-street-map"><i class="fa fa-check"></i><b>16.4</b> Open Street Map</a></li>
<li class="chapter" data-level="16.5" data-path="appendix-c-sourcing-geographical-data-for-crime-analysis.html"><a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html#summary-and-further-reading-12"><i class="fa fa-check"></i><b>16.5</b> Summary and further reading</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Crime Mapping and Spatial Data Analysis using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendix-b-regression-analysis-a-refresher" class="section level1 hasAnchor" number="15">
<h1><span class="header-section-number">Chapter 15</span> Appendix B: Regression analysis (a refresher)<a href="appendix-b-regression-analysis-a-refresher.html#appendix-b-regression-analysis-a-refresher" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-11" class="section level2 hasAnchor" number="15.1">
<h2><span class="header-section-number">15.1</span> Introduction<a href="appendix-b-regression-analysis-a-refresher.html#introduction-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this appendix we present a very brief and high-level overview of regression analysis, in order to give some reference to when we introduce spatial regression in Chapter 11. We will follow a practical approach, working through one data set to illustrate regression basics using R. For those who wish to have a more thorough grounding please refer to the further reading section at the end of this Appendix.</p>
<p>Here we will return to the “ncovr” data set produced as part of the National Consortium on Violence Research (NCOVR) agenda (we use this also in Chapters 11 and 11, for more information on this data see <span class="citation">Baller et al. (<a href="#ref-Baller_2001" role="doc-biblioref">2001</a>)</span>). The data set includes variables related to homicides in the US, as well as information in a number of sociodemographic variables that are often thought of as associated with the geographical distribution of homicides. This data set is available as part of the <code>geodaData</code> package.</p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb680-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb680-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geodaData)</span>
<span id="cb680-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb680-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ncovr&quot;</span>)</span></code></pre></div>
<p>The dataset contains information about 3085 counties in the United States and if you view it you will see it has information about several decades, the 60s, 70s, 80s, and 90s. The number at the end of the variable names denotes the relevant decade and you will see that for each decade we have the same variables.</p>
<p>The purpose of regression analysis as we approach it here is to choose a model to represent the relationship between homicide and various predictors. You can think of a model as a map. A map aims to represent a given reality, but as you may have already discovered there are many ways of presenting the same information through a map. As an analyst you decide what the most appropriate representation for your needs is. Each representation you choose will involve an element of distortion. Maps (and models) are not exact representations of the real word, they are simply good approximations that may serve well a particular functional need. You may think about the map of the London Underground. It doesn’t show you geographically where the Underground lines of London are, yet, if you want to use the Metro system, this map will be extremely helpful to you. It serves a need in a good way. The same happens with models. They may not be terribly good reflections of the world, but may give us approximations that allows us to develop useful insights.</p>
<p>Choosing a good model is like choosing a good way for displaying quantitative information in a map. Decisions, decisions, decisions. There are many parameters and options one can choose from. This can be overwhelming, particularly as you are learning how to model and map phenomena. How to make good decisions is something that you learn on earnest by practice, practice, practice. Nobody expects you to get the maps you are doing as you are learning, and the models you are developing as you are learning spot on. So please do not stress out about this. All we can do here is to learn some basic principles and start getting some practice, which you will be able to further develop in a professional context or in further training.</p>
<p>The first step in any analysis is to develop some familiarity with the data you are going to be working with. We have been here before. Read the codebook. Run summary statistics for your quantitative variables, frequency distributions for your categorical variables, and visualise your variables. This will help you to detect any anomalies and give you a sense for what you have. If, for example, you run a histogram for the homicide rate for 1990 (HR90), you will get a sense of the distribution form –which of course is skewed.</p>
<div class="sourceCode" id="cb681"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb681-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb681-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb681-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb681-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x =</span> HR90, <span class="at">data =</span> ncovr)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-416"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-416-1.png" alt="A bar plot of grey bars over a light grey grid. The vertical axis ranges from zero to eight hundred, and the horizontal axis, labeled 'HR90' from zero to eighty. The first bar, centred at zero, reaches over seven hundred and fifty, and the bars decrease in height nearly linearly until the fifth bar centred around ten reaches two hundred and fifty. The bars continue to decrease in height slower, and become small slivers past thirty." width="672" />
<p class="caption">
FIGURE 15.1: Histogram of the HR90 variable
</p>
</div>
<p>Once one has gone through the process of exploring the data in this way (or maybe using the <code>skimr</code> package - see <em>Appendix: A quick intro to R and RStudio</em>) for all the variables you want to work with, you can start exploring bivariate associations with your dependent, response or outcome variable. So, as an illustration, you could explore the association with resource deprivation (<em>RD90</em>), a measure of the level of concentrated disadvantage or social exclusion in an area, via a scatterplot:</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb682-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ncovr, <span class="fu">aes</span>(<span class="at">x =</span> RD90, <span class="at">y =</span> HR90)) <span class="sc">+</span></span>
<span id="cb682-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb682-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span>.<span class="dv">2</span>) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-417"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-417-1.png" alt="A plot of black circles on a grey grid, with the vertical axis, labeled 'HR90' ranging from zero to seventy. The horizontal axis is labeled 'RD90' and ranges from negative three to six. Points cluster around the area from negative one to zero, under a value of ten. A general pattern of increase can be seen." width="672" />
<p class="caption">
FIGURE 15.2: Scatterplot showing relationship between resource deprivation (RD90) and homicide rate (HR90) in the 90s
</p>
</div>
<p>What do you think when looking at this scatterplot? Is there a relationship between the variables? Does it look as if individuals that have a high score on the X axis also have a high score on the Y axis? Or viceversa?</p>
</div>
<div id="motivating-regression" class="section level2 hasAnchor" number="15.2">
<h2><span class="header-section-number">15.2</span> Motivating regression<a href="appendix-b-regression-analysis-a-refresher.html#motivating-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now, imagine that we play a game. Imagine I have all the respondents waiting in a room, and I randomly call one of them to the stage. You’re sitting in the audience, and you have to guess the level of homicide (<em>HR90</em>) for that respondent. Imagine that I pay £150 to the student that gets the closest to the right value. What would you guess if you only have one guess and you knew (as we do) how homicide in the 90s is distributed?</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb683-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ncovr, <span class="fu">aes</span>(<span class="at">x =</span> HR90)) <span class="sc">+</span> </span>
<span id="cb683-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb683-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb683-3"><a href="appendix-b-regression-analysis-a-refresher.html#cb683-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(ncovr<span class="sc">$</span>HR90), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, </span>
<span id="cb683-4"><a href="appendix-b-regression-analysis-a-refresher.html#cb683-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> <span class="co"># median = 4.377</span></span>
<span id="cb683-5"><a href="appendix-b-regression-analysis-a-refresher.html#cb683-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(ncovr<span class="sc">$</span>HR90), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, </span>
<span id="cb683-6"><a href="appendix-b-regression-analysis-a-refresher.html#cb683-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">+</span> <span class="co"># mean = 6.183</span></span>
<span id="cb683-7"><a href="appendix-b-regression-analysis-a-refresher.html#cb683-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Density estimate, mean and median of homicide rate 1990&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-418"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-418-1.png" alt="A black plot over a grey grid, titled 'Density estimate, mean and median of homicide rate 1990. The vertical axis is labeled 'density', and runs from zero to point one, while the horizontal axis is labeled 'HR90', and runs from zero to seventy five. Two dashed horizontal lines appear close to five, coloured red and blue. The plotted data, starting at zero with a value of point one, has a small hook before dropping down gradually." width="672" />
<p class="caption">
FIGURE 15.3: Density estimate, mean, and median of homicide rate in 1990
</p>
</div>
<div class="sourceCode" id="cb684"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb684-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb684-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ncovr<span class="sc">$</span>HR90)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    1.33    4.38    6.18    8.94   71.38</code></pre>
<p>If I only had one shot, you could go for the median, in red, (given the skew) but the mean, in blue, perhaps would be your second best. Most of the areas here have values clustered around those values, which is another way of saying they are bound to be not too far from them.</p>
<p>Imagine, however, that now when someone is called to the stage, you are told the level of resource deprivation in the county - so the value of the <em>RD90</em> variable for the individual that has been selected (for example 4). Imagine as well that you have the scatterplot that we produced earlier in front of you. Would you still go for the value of “4.377” as your best guess for the value of the selected county?</p>
<p>I certainly would not go with the overall mean or median as my prediction anymore. If somebody said to me, the value <em>RD90</em> for the selected respondent is 4, I would be more inclined to guess the mean value for the level of homicide with that level of resource deprivation (the conditional mean), rather than the overall mean across all the counties. Wouldn’t you?</p>
<p>If we plot the conditional means we can see that the mean of homicide rate for counties that report a value of 4 in <em>RD90</em> is around 22. So you may be better off guessing that.</p>
<div class="sourceCode" id="cb686"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb686-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(grid)</span>
<span id="cb686-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb686-3"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>ncovr, <span class="fu">aes</span>(<span class="at">x =</span> RD90, <span class="at">y =</span> HR90), <span class="at">alpha=</span>.<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb686-4"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-4" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="at">data=</span>ncovr, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">round</span>(RD90<span class="sc">/</span><span class="fl">0.12</span>)<span class="sc">*</span><span class="fl">0.12</span>, <span class="at">y =</span> HR90),</span>
<span id="cb686-5"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">stat=</span><span class="st">&#39;summary&#39;</span>, <span class="at">fun.y=</span>mean, <span class="at">color=</span><span class="st">&quot;red&quot;</span>, <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb686-6"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;segment&quot;</span>, <span class="at">x=</span><span class="dv">3</span>, <span class="at">xend =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="dv">25</span>, <span class="at">yend=</span> <span class="dv">22</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, </span>
<span id="cb686-7"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">size =</span> <span class="dv">2</span>, <span class="at">arrow =</span> <span class="fu">arrow</span>()) <span class="sc">+</span></span>
<span id="cb686-8"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="dv">29</span>, <span class="at">label =</span> <span class="st">&quot;Pick this one!&quot;</span>, </span>
<span id="cb686-9"><a href="appendix-b-regression-analysis-a-refresher.html#cb686-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">size =</span><span class="dv">7</span>, <span class="at">colour =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-420"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-420-1.png" alt="The scatterplot from before now has a red line plotted on it, generally increasing from left to right. It increases more smoothly where there are more points plotted, and jumps up and down once the data becomes sparse at higher RD90. At an RD90 value of 4, the red line has a value of around 22. A blue arrow with the text 'Pick this one!' is overlaid on the plot, pointing to this spot." width="672" />
<p class="caption">
FIGURE 15.4: Our best guess for homicide rate when resource deprivation score in the county is 4
</p>
</div>
<p>Linear regression tackles this problem using a slightly different approach. Rather than focusing on the conditional mean (smoothed or not), it draws a straight line that tries to capture the trend in the data. If we focus in the region of the scatterplot that are less sparse we see that this is an upward trend, suggesting that as resource deprivation increases so does the homicide rate.</p>
<p>Simple linear regression draws a single straight line of predicted values as the model for the data. This line would be a <strong>model</strong>, a <em>simplification</em> of the real world like any other model (e.g., a toy pistol, an architectural drawing, a subway map), that assumes that there is approximately a linear relationship between X and Y. Let’s draw the regression line using the function <code>geom_smooth()</code>. This ask for a <code>method=</code> parameter where we specify <code>lm</code> for the linear regression line. We also set <code>se=</code> to <code>FALSE</code> so we ask for just the line to be printed but not the standard error around it. The other arguments specify the color and thickness of the line.</p>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb687-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ncovr, <span class="fu">aes</span>(<span class="at">x =</span> RD90, <span class="at">y =</span> HR90)) <span class="sc">+</span></span>
<span id="cb687-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb687-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb687-3"><a href="appendix-b-regression-analysis-a-refresher.html#cb687-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-421"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-421-1.png" alt="This time the previous scatterplot has a straight red line with positive slope through it, cutting the dataset into half, more or less." width="672" />
<p class="caption">
FIGURE 15.5: Linear regression line on relationship between homicide rate and resource deprivation
</p>
</div>
<p>What that line is doing is giving you guesses (predictions) for the values of homicide based in the information that we have about the level of resource deprivation. It gives you one possible guess for the value of homicide for every possible value of resource deprivation and links them all together in a straight line.</p>
<p>The linear model then is a model that takes the form of the equation of a straight line through the data. The line does not go through all the points.</p>
<p>Our regression line underpredicts at low levels of resource deprivation and does not seem to capture well the variability at higher levels of resource deprivation. But imperfect as a model as it might be it simplifies well the overall growing trend for homicide as resource deprivation increases.</p>
<p>As <span class="citation">Veaux, Velleman, and Bock (<a href="#ref-DeVeaux_2012" role="doc-biblioref">2012</a>)</span> highlight: “like all models of the real world, the line will be wrong, wrong in the sense that it can’t match reality exactly. But it can help us understand how the variables are associated” (p. 179). A map is never a perfect representation of the world, the same happens with statistical models. Yet, as with maps, models can be helpful.</p>
</div>
<div id="fitting-a-simple-regression-model" class="section level2 hasAnchor" number="15.3">
<h2><span class="header-section-number">15.3</span> Fitting a simple regression model<a href="appendix-b-regression-analysis-a-refresher.html#fitting-a-simple-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In order to draw a regression line (or in fact any line in a Cartesian coordinate system) we need to know two things:</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>We need to know where the line begins, what is the value of Y (our dependent variable) when X (our independent variable) is 0, so that we have a point from which to start drawing the line. The technical name for this point is the <strong>intercept</strong>.</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>And we need to know what is the <strong>slope</strong> of that line, that is, how inclined the line is, the angle of the line.</li>
</ol></li>
</ul>
<p>If you recall from elementary algebra (and you may not), the equation for any straight line is: <span class="math inline">\(y = mx + b\)</span> . In statistics we use a slightly different notation, although the equation remains the same: <span class="math inline">\(y = \beta_0 + \beta_1x\)</span>.</p>
<p>We need the origin of the line (<span class="math inline">\(\beta_0\)</span>) and the slope of the line (<span class="math inline">\(\beta_1\)</span>). How does R get the intercept and the slope for the green line? How does R know where to draw this line? We need to estimate these <strong>parameters</strong> (or <strong>coefficients</strong>) from the data. How? We don’t have the time to get into these more mathematical details now, but will suggest further reading at the end of this appendix for the curious. For now, suffice to say that for linear regression modes like the one we cover here, when drawing the line, R tries to minimise the distance from every point in the scatterplot to the regression line using a method called <strong>least squares estimation</strong>.</p>
<p>In order to fit the model we use the <code>lm()</code> function using the formula specification <span class="math inline">\((Y ~ X)\)</span>. Typically you want to store your regression model in a “variable”, let’s call it <code>fit_1</code>:</p>
<div class="sourceCode" id="cb688"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb688-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb688-1" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR90 <span class="sc">~</span> RD90, <span class="at">data =</span> ncovr)</span></code></pre></div>
<p>You will see in your R Studio global environment space that there is a new object called <code>fit_1</code> with 12 elements on it. We can get a sense for what this object is and includes using the functions we introduced in previous weeks:</p>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb689-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(fit_1)</span></code></pre></div>
<pre><code>## [1] &quot;lm&quot;</code></pre>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb691-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(fit_1)</span></code></pre></div>
<pre><code>## $names
##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;      
##  [4] &quot;rank&quot;          &quot;fitted.values&quot; &quot;assign&quot;       
##  [7] &quot;qr&quot;            &quot;df.residual&quot;   &quot;xlevels&quot;      
## [10] &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;        
## 
## $class
## [1] &quot;lm&quot;</code></pre>
<p>R is telling us that this is an object of class <code>lm</code> and that it includes a number of attributes. One of the beauties of R is that you are producing all the results from running the model, putting them in an object, and then giving you the opportunity for using them later on. If you want to simply see the basic results from running the model you can use the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb693"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb693-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb693-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90, data = ncovr)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -17.80  -3.42  -0.72   2.54  67.10 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   6.1829     0.0984    62.8   &lt;2e-16 ***
## RD90          3.7712     0.0985    38.3   &lt;2e-16 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.47 on 3083 degrees of freedom
## Multiple R-squared:  0.322,  Adjusted R-squared:  0.322 
## F-statistic: 1.47e+03 on 1 and 3083 DF,  p-value: &lt;2e-16</code></pre>
<p>Or if you prefer more parsimonious presentation you could use the <code>display()</code> function of the <code>arm</code> package:</p>
<div class="sourceCode" id="cb695"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb695-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb695-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arm)</span>
<span id="cb695-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb695-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb695-3"><a href="appendix-b-regression-analysis-a-refresher.html#cb695-3" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(fit_1)</span></code></pre></div>
<pre><code>## lm(formula = HR90 ~ RD90, data = ncovr)
##             coef.est coef.se
## (Intercept) 6.18     0.10   
## RD90        3.77     0.10   
## ---
## n = 3085, k = 2
## residual sd = 5.47, R-Squared = 0.32</code></pre>
<p>For now I just want you to focus on the numbers in the “Estimate” (or coef.est) column. The value of 6.18 estimated for the <strong>intercept</strong> is the “predicted” value for Y when X equals zero. This is the predicted value of the fear of crime score <em>when resource deprivation has a value of zero</em>.</p>
<div class="sourceCode" id="cb697"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb697-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb697-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ncovr<span class="sc">$</span>RD90)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  -2.410  -0.667  -0.202   0.000   0.439   5.583</code></pre>
<p>RD90 is a variable that has been centered in 0. It has been created by the researchers in such a way that is has a mean value of 0. Since we only have one explanatory variable in the model this corresponds to the mean of the homicide rate, 6.18. In many other contexts the intercept has less of a meaning.</p>
<p>We then need the b1 regression coefficient for our independent variable, the value that will shape the <strong>slope</strong> in this scenario. This value is 3.77. This estimated regression coefficient for our independent variable has a convenient interpretation. When the value is positive, it tells us that <em>for every one unit increase in X there is a b1 increase on Y</em>. If the coefficient is negative then it represents a decrease on Y. Here, we can read it as “for every one unit increase in the resource deprivation score, there is a 3.77 unit increase in the homicide rate.”</p>
<p>Knowing these two parameters not only allows us to draw the line, we can also solve for any given value of X. Let’s go back to our guess-the-homicide-rate game. Imagine I tell you the level of resource deprivation is 1. What would be your best bet now? We can simply go back to our regression line equation and insert the estimated parameters:</p>
<p><span class="math display">\[y = b_0 + b_1x\]</span>
<span class="math display">\[y = 6.18 + 3.77 \times 1\]</span><br />
<span class="math display">\[y = 9.95\]</span></p>
<p>Or if you don’t want to do the calculation yourself, you can use the <code>predict()</code> function (differences are due to rounding error). First you name your stored model and then you identify the new data (which has to be in a data frame format and with a variable name matching the one in the original data set).</p>
<div class="sourceCode" id="cb699"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb699-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb699-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit_1, <span class="fu">data.frame</span>(<span class="at">RD90 =</span> <span class="fu">c</span>(<span class="dv">1</span>))) </span></code></pre></div>
<pre><code>##     1 
## 9.954</code></pre>
<p>This is the expected value of Y, homicide rate, when X, resource deprivation is 1 <strong>according to our model</strong> (according to our simplification of the real world, our simplification of the whole cloud of points into just one straight line). Look back at the scatterplot we produced earlier with the red line. Does it look as if the green line when X is 1 corresponds to a value of Y of 9.95?</p>
</div>
<div id="residuals-revisited-r-squared" class="section level2 hasAnchor" number="15.4">
<h2><span class="header-section-number">15.4</span> Residuals revisited: R squared<a href="appendix-b-regression-analysis-a-refresher.html#residuals-revisited-r-squared" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the output above we saw there was something called the residuals. The residuals are the differences between the observed values of Y for each case minus the predicted or expected value of Y, in other words the distances between each point in the dataset and the regression line (see the visual example below).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-428"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-428-1.png" alt="A plot of black points and a blue regression line. One point is focused on, and a rounded box with label 'Measured value' identifies it. It lies a little ways above the blue line. A red vertical dashed line segment connects it to the line, and this segment is labeled as the 'Residual'. This red dashed line hits the blue line at a point which is labeled as the 'Predicted value'." width="672" />
<p class="caption">
FIGURE 15.6: Predicted values, measured value, and residual
</p>
</div>
<p>You see that we have our line, which is our predicted values, and then we have the black dots which are our actually observed values. The distance between them is essentially the amount by which we were wrong, and all these distances between observed and predicted values are our residuals. Least square estimation essentially aims to reduce the average of the squares of all these distances: that’s how it draws the line.</p>
<p>Why do we have residuals? Well, think about it. The fact that the line is not a perfect representation of the cloud of points makes sense, doesn’t it? You cannot predict perfectly what the value of Y is for every observation just by looking ONLY at their level of resource deprivation! This line only uses information regarding resource deprivation. This means that there’s bound to be some difference between our predicted level of homicide given our knowledge of deprivation (the regression line) and the actual level of homicide (the actual location of the points in the scatterplot). There are other things that matter not being taken into account by our model to predict the values of Y. There are other things that surely matter in terms of understanding homicide. And then, of course, we have measurement error and other forms of noise.</p>
<p>We can re-write our equation like this if we want to represent each value of Y (rather than the predicted value of Y) then:
<span class="math inline">\(y = \beta_0 + \beta_1x + \text{residuals}\)</span></p>
<p>The residuals capture how much variation is unexplained, how much we still have to learn if we want to understand variation in Y. A good model tries to maximise explained variation and reduce the magnitude of the residuals.</p>
<p>We can use information from the residuals to produce a measure of effect size, of how good our model is in predicting variation in our dependent variables. Remember our game where we try to guess homicide (Y)? If we did not have any information about X our best bet for Y would be the mean of Y. The regression line aims to improve that prediction. By knowing the values of X we can build a regression line that aims to get us closer to the actual values of Y (look at the Figure below).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-429"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-429-1.png" alt="The previous plot of black points and blue line has gained more dashed lines, and explanations. Three horizontal dashed lines appear, the topmost one, labeled 'Actual Y', is intersecting our chosen data point. The next is labeled as 'Predicted Y', and is intersecting our blue line at our previous predicted value point. The third one is labeled 'Mean of T', and is further down. The distance between the first two lines, actual and predicted Y, is labeled 'Unexplained deviation (residual)'. The distance between predicted and the mean has label 'Explained deviation (regression). The sum of these, and distance between actual Y and mean of Y, is labeled 'Total deviation'." width="672" />
<p class="caption">
FIGURE 15.7: Illustration of explained, unexplained, and total deviation
</p>
</div>
<p>The distance between the mean (our best guess without any other piece of information) and the observed value of Y is what we call the <strong>total variation</strong>. The residual is the difference between our predicted value of Y and the observed value of Y. This is what we cannot explain (i.e, variation in Y that is <em>unexplained</em>). The difference between the mean value of Y and the expected value of Y (the value given by our regression line) is how much better we are doing with our prediction by using information about X (i.e., in our previous example it would be variation in Y that can be <em>explained</em> by knowing about resource deprivation). How much closer the regression line gets us to the observed values. We can then contrast these two different sources of variation (explained and unexplained) to produce a single measure of how good our model is. The formula is as follows:</p>
<p><span class="math display">\[R^2 = \dfrac{SSR}{SST} = \dfrac{\Sigma(\hat y_i - \bar y )^2}{\Sigma(y_i - \bar y )^2}\]</span></p>
<p>All this formula is doing is taking a ratio of the explained variation (the squared differences between the regression line and the mean of Y for each observation) by the total variation (the squared differences of the observed values of Y for each observation from the mean of Y). This gives us a measure of the <strong>percentage of variation in Y that is “explained” by X</strong>. If this sounds familiar is because it is a measure similar to eta squared (<span class="math inline">\(eta^2\)</span>) in ANOVA.</p>
<p>As then we can take this value as a measure of the strength of our model. If you look at the R output you will see that the R2 for our model was .32 (look at the multiple R square value in the output) . We can say that our model explains 32% of the variance in the fear of homicide. when doing regression, you will often find that regression models with aggregate data such as county level data will give you better results than when dealing with individuals. It is much harder understanding individual variation than county level variation.</p>
<p>As an aside, and to continue emphasising your appreciation of the object oriented nature of R, when we run the <code>summary()</code> function we are simply generating a list object of the class summary.lm.</p>
<div class="sourceCode" id="cb701"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb701-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb701-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(<span class="fu">summary</span>(fit_1))</span></code></pre></div>
<pre><code>## $names
##  [1] &quot;call&quot;          &quot;terms&quot;         &quot;residuals&quot;    
##  [4] &quot;coefficients&quot;  &quot;aliased&quot;       &quot;sigma&quot;        
##  [7] &quot;df&quot;            &quot;r.squared&quot;     &quot;adj.r.squared&quot;
## [10] &quot;fstatistic&quot;    &quot;cov.unscaled&quot; 
## 
## $class
## [1] &quot;summary.lm&quot;</code></pre>
<p>This means that we can access its elements if so we wish. So, for example, to obtain just the R Squared (<span class="math inline">\(R^2\)</span>), we could ask for:</p>
<div class="sourceCode" id="cb703"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb703-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb703-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_1)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.3224</code></pre>
<p>Knowing how to interpret this is important. <span class="math inline">\(R^2\)</span> ranges from 0 to 1. The greater it is the more powerful our model is, the more explaining we are doing, the better we are able to account for variation in our outcome Y with our input. In other words, the stronger the relationship is between Y and X. As with all the other measures of effect size interpretation is a matter of judgment. You are advised to see what other researchers report in relation to the particular outcome that you may be exploring.</p>
<p><span class="citation">Weisburd and Britt (<a href="#ref-Weisburd_2014" role="doc-biblioref">2014</a>)</span> suggest that in criminal justice you rarely see values for <span class="math inline">\(R^2\)</span> greater than .40. Thus, if your <span class="math inline">\(R^2\)</span> is larger than .40, you can assume you have a powerful model. When, on the other hand, <span class="math inline">\(R^2\)</span> is lower than .15 or .2 the model is likely to be viewed as relatively weak. Our observed r squared here is rather poor. There is considerably room for improvement if we want to develop a better model to explain fear of violent crime. In any case, many people would argue that <span class="math inline">\(R^2\)</span> is a bit overrated. You need to be aware of what it measures and the context in which you are using it.</p>
</div>
<div id="inference-with-regression" class="section level2 hasAnchor" number="15.5">
<h2><span class="header-section-number">15.5</span> Inference with regression<a href="appendix-b-regression-analysis-a-refresher.html#inference-with-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In real applications, we have access to a set of observations from which we can compute the least squares line, but the population regression line is unobserved. So our regression line is one of many that could be estimated. A different sample would produce a different regression line. The same sort of ideas that we introduced when discussing the estimation of sample means or proportions also apply here. if we estimate b0 and b1 from a particular sample, then our estimates won’t be exactly equal to b0 and b1 in the population. But if we could average the estimates obtained over a very large number of data sets, the average of these estimates would equal the coefficients of the regression line in the population.</p>
<p>We can compute standard errors for the regression coefficients to quantify our uncertainty about these estimates. These standard errors can in turn be used to produce confidence intervals. This would require us to assume that the residuals are normally distributed. For a simple regression model, you are assuming that the values of Y are approximately normally distributed for each level of X. In those circumstances we can trust the confidence intervals that we can draw around the regression line.</p>
<p>You can also then perform standard hypothesis test on the coefficients. As we saw before when summarising the model, R will compute the standard errors and a t test for each of the coefficients.</p>
<div class="sourceCode" id="cb705"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb705-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb705-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_1)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##             Estimate Std. Error t value   Pr(&gt;|t|)
## (Intercept)    6.183    0.09844   62.81  0.000e+00
## RD90           3.771    0.09846   38.30 6.536e-263</code></pre>
<p>In our example, we can see that the coefficient for our predictor here is statistically significant.</p>
<p>We can also obtain confidence intervals for the estimated coefficients using the <code>confint()</code> function:</p>
<div class="sourceCode" id="cb707"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb707-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb707-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit_1)</span></code></pre></div>
<pre><code>##             2.5 % 97.5 %
## (Intercept) 5.990  6.376
## RD90        3.578  3.964</code></pre>
</div>
<div id="fitting-regression-with-categorical-predictors" class="section level2 hasAnchor" number="15.6">
<h2><span class="header-section-number">15.6</span> Fitting regression with categorical predictors<a href="appendix-b-regression-analysis-a-refresher.html#fitting-regression-with-categorical-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far we have explained regression using a numeric input. It turns out we can also use regression with categorical explanatory variables. It is quite straightforward to run it.</p>
<p>There is only one categorical explanatory variable in this dataset, a binary indicator that indicates whether the county is in a Southern State or not. We can also explore this relationship using regression and a regression line. This is how you would express the model:</p>
<div class="sourceCode" id="cb709"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb709-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb709-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We use the as.factor function to tell R that SOUTH is a categorical variable</span></span>
<span id="cb709-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb709-2" aria-hidden="true" tabindex="-1"></a>fit_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR90 <span class="sc">~</span> <span class="fu">as.factor</span>(SOUTH), <span class="at">data=</span>ncovr)</span></code></pre></div>
<p>Notice that there is nothing different in how we ask for the model.</p>
<p>Let’s have a look at the results:</p>
<div class="sourceCode" id="cb710"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb710-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb710-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ as.factor(SOUTH), data = ncovr)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -9.55  -3.34  -1.17   1.93  68.04 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)          3.342      0.144    23.2   &lt;2e-16
## as.factor(SOUTH)1    6.208      0.212    29.2   &lt;2e-16
##                      
## (Intercept)       ***
## as.factor(SOUTH)1 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.88 on 3083 degrees of freedom
## Multiple R-squared:  0.217,  Adjusted R-squared:  0.217 
## F-statistic:  854 on 1 and 3083 DF,  p-value: &lt;2e-16</code></pre>
<p>As you will see the output does not look too different. But notice that in the print out you see how the row with the coefficient and other values for our input variable <code>SOUTH</code> we see that R is printing <code>1</code>. What does this mean?</p>
<p>It turns out that a linear regression model with just one dichotomous categorical predictor is just the equivalent of a t test. When you only have one predictor the value of the intercept is the mean value of the <strong>reference category</strong> and the coefficient for the slope tells you how much higher (if it is positive) or how much lower (if it is negative) is the mean value for the other category in your factor.</p>
<p>The reference category is the one for which R does not print the <em>level</em> next to the name of the variable for which it gives you the regression coefficient. Here we see that the named level is “1”. That’s telling you that the reference category here is “0”. If you look at the codebook you will see that 1 means the county is in a Southern state. Therefore the Y intercept in this case is the mean value of fear of violent crime for the northern counties, whereas the coefficient for the slope is telling you how much higher (since it is a positive value) the mean value is for the southern counties. Don’t believe me?</p>
<div class="sourceCode" id="cb712"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb712-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb712-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ncovr<span class="sc">$</span>HR90[ncovr<span class="sc">$</span>SOUTH <span class="sc">==</span> <span class="dv">0</span>], <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.342</code></pre>
<div class="sourceCode" id="cb714"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb714-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb714-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ncovr<span class="sc">$</span>HR90[ncovr<span class="sc">$</span>SOUTH <span class="sc">==</span> <span class="dv">1</span>], <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">mean</span>(ncovr<span class="sc">$</span>HR90[ncovr<span class="sc">$</span>SOUTH <span class="sc">==</span> <span class="dv">0</span>], <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 6.208</code></pre>
<p>So, to reiterate, for a binary predictor, the coefficient is nothing else than the difference between the mean of the two levels in your factor variable, between the averages in your two groups.</p>
<p>With categorical variables encoded as <strong>factors</strong> you always have a situation like this: a reference category and then as many additional coefficients as there are additional levels in your categorical variable. Each of these additional categories is included into the model as <strong>“dummy” variables</strong>. Here our categorical variable has two levels, thus we have only one dummy variable. There will always be one fewer dummy variable than the number of levels. The level with no dummy variable, northern counties in this example, is known as the <strong>reference category</strong> or the <strong>baseline</strong>.</p>
<p>It turns out then that the regression table is printing out for us a t test of statistical significance for every input in the model. If we look at the table above this t value is 29.22 and the p value associated with it is near 0. This is indeed considerably lower than the conventional significance level of 0.05. So we could conclude that the probability of obtaining this value if the null hypothesis is true is very low. The r squared is not too bad either, although lower than we saw when using resource deprivation.</p>
</div>
<div id="motivating-multiple-regression" class="section level2 hasAnchor" number="15.7">
<h2><span class="header-section-number">15.7</span> Motivating multiple regression<a href="appendix-b-regression-analysis-a-refresher.html#motivating-multiple-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So we have seen that we can fit models with just one predictor. We can build better models by expanding the number of predictors (although keep in mind you should also aim to build models as parsimonious as possible).</p>
<p>Another reason why it is important to think about additional variables in your model is to control for spurious correlations (although here you may also want to use your common sense when selecting your variables!). You must have heard before that correlation does not equal causation. Just because two things are associated we cannot assume that one is the cause for the other. Typically we see how the pilots switch the secure the belt button when there is turbulence. These two things are associated, they tend to come together. But the pilots are not causing the turbulences by pressing a switch! The world is full of <strong>spurious correlations</strong>, associations between two variables that should not be taking too seriously. You can explore a few <a href="http://tylervigen.com/">here</a>. It’s funny.</p>
<p>Looking only at covariation between pair of variables can be misleading. It may lead you to conclude that a relationship is more important than it really is. This is no trivial matter, but one of the most important ones we confront in research and policy.</p>
<p>It’s not an exaggeration to say that most quantitative explanatory research is about trying to control for the presence of <strong>confounders</strong>, variables that may explain explain away observed associations. Think about any criminology question: Does marriage reduces crime? Or is it that people that get married are different from those that don’t (and are those pre-existing differences that are associated with less crime)? Do gangs lead to more crime? Or is it that young people that join gangs are more likely to be offenders to start with? Are the police being racist when they stop and search more members of ethnic minorities? Or is it that there are other factors (i.e., offending, area of residence, time spent in the street) that, once controlled, would mean there is no ethnic dis-proportionality in stop and searches? Does a particular program reduces crime? Or is the observed change due to something else?</p>
<p>These things also matter for policy. <span class="citation">Wilson and Kelling (<a href="#ref-Wilson_1982" role="doc-biblioref">1982</a>)</span>, for example, argued that signs of incivility (or antisocial behaviour) in a community lead to more serious forms of crime later on as people withdraw to the safety of their homes when they see those signs of incivilities and this leads to a reduction in informal mechanisms of social control. All the policies to tackle antisocial behaviour in this country are very much informed by this model and were heavily influenced by broken windows theory.</p>
<p>But is the model right? <span class="citation">Sampson, Raudenbush, and Earls (<a href="#ref-Sampson_1997" role="doc-biblioref">1997</a>)</span> argue it is not entirely correct. They argue, and tried to show, that there are other confounding factors (poverty, collective efficacy) that explain the association of signs of incivility and more serious crime. In other words, the reason why you see antisocial behaviour in the same communities that you see crime is because other structural factors explain both of those outcomes. They also argue that perceptions of antisocial behaviour are not just produced by observed antisocial behaviour but also by stereotypes about social class and race. If you believe them, then the policy implications are that only tackling antisocial behaviour won’t help you to reduce crime (as <span class="citation">Wilson and Kelling (<a href="#ref-Wilson_1982" role="doc-biblioref">1982</a>)</span> have argued) . So as you can see this stuff matters for policy not just for theory.</p>
<p>Multiple regression is one way of checking the relevance of competing explanations. You could set up a model where you try to predict crime levels with an indicator of broken windows and an indicator of structural disadvantage. If after controlling for structural disadvantage you see that the regression coefficient for broken windows is still significant you may be into something, particularly if the estimated effect is still large. If, on the other hand, the t test for the regression coefficient of your broken windows variable is no longer significant, then you may be tempted to think that perhaps <span class="citation">Sampson, Raudenbush, and Earls (<a href="#ref-Sampson_1997" role="doc-biblioref">1997</a>)</span> were into something.</p>
</div>
<div id="fitting-and-interpreting-a-multiple-regression-model" class="section level2 hasAnchor" number="15.8">
<h2><span class="header-section-number">15.8</span> Fitting and interpreting a multiple regression model<a href="appendix-b-regression-analysis-a-refresher.html#fitting-and-interpreting-a-multiple-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It could not be any easier to fit a multiple regression model. You simply modify the formula in the <code>lm()</code> function by adding terms for the additional inputs.</p>
<div class="sourceCode" id="cb716"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb716-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb716-1" aria-hidden="true" tabindex="-1"></a>ncovr<span class="sc">$</span>SOUTH_f <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(ncovr<span class="sc">$</span>SOUTH)</span>
<span id="cb716-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb716-2" aria-hidden="true" tabindex="-1"></a>fit_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR90 <span class="sc">~</span> RD90 <span class="sc">+</span> SOUTH_f, <span class="at">data=</span>ncovr)</span>
<span id="cb716-3"><a href="appendix-b-regression-analysis-a-refresher.html#cb716-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90 + SOUTH_f, data = ncovr)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -16.48  -3.00  -0.58   2.22  68.15 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    4.727      0.139    33.9   &lt;2e-16 ***
## RD90           2.965      0.111    26.8   &lt;2e-16 ***
## SOUTH_f1       3.181      0.222    14.3   &lt;2e-16 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.3 on 3082 degrees of freedom
## Multiple R-squared:  0.365,  Adjusted R-squared:  0.364 
## F-statistic:  884 on 2 and 3082 DF,  p-value: &lt;2e-16</code></pre>
<p>With more than one input, you need to ask yourself whether all of the regression coefficients are zero. This hypothesis is tested with a F test. Again we are assuming the residuals are normally distributed, though with large samples the F statistics approximates the F distribution. You see the F test printed at the bottom of the summary output and the associated p value, which in this case is way below the conventional .05 that we use to declare statistical significance and reject the null hypothesis. At least one of our inputs must be related to our response variable.</p>
<p>Notice that the table printed also reports a t test for each of the predictors. These are testing whether each of these predictors is associated with the response variable when adjusting for the other variables in the model. They report the “partial effect of adding that variable to the model” <span class="citation">(<a href="#ref-James_2013" role="doc-biblioref">James et al. 2013</a>: 77)</span>. In this case we can see that both variables seem to be significantly associated with the response variable.</p>
<p>If we look at the r squared we can now see that it is higher than before. r squared will always increase as a consequence of adding new variables, even if the new variables added are weakly related to the response variable.</p>
<p>We see that the coefficients for the predictors change somehow, it goes down a bit for <em>RD90</em> and it halves for <em>SOUTH</em>. <strong>But their interpretation now changes</strong>. A common interpretation is that now the regression for each variable tells you about changes in Y related to that variable <strong>when the other variables in the model are held constant</strong>. So, for example, you could say the coefficient for <em>RD90</em> represents the increase in homicide for every one-unit increase in the measure of resource deprivation <em>when holding all other variables in the model constant</em> (in this case that refers to holding constant <em>SOUTH</em>). But this terminology can be a bit misleading.</p>
<p>Other interpretations are also possible and are more generalizable. <span class="citation">Gelman and Hill (<a href="#ref-Gelman_2007" role="doc-biblioref">2007</a>)</span> emphasise what they call the <em>predictive interpretation</em> that considers how “the outcome variable differs, on average, when comparing two groups of units that differ by 1 in the relevant predictor while being identical in all the other predictors” (p. 34). So if you’re regressing y on u and v, the coefficient of u is the average difference in y per difference in u, comparing pairs of items that differ in u but are identical in v.</p>
<p>For example, in this case we could say that comparing counties that have the same level of resource deprivation but that differed in whether they are South or North, the model predicts a expected difference of 3.18 in their homicide rate. And that respondents that do not vary in whether they are South or North, but that differ by one point in the level of resource deprivation, we would expect to see a difference of 2.96 in their homicide rate. So we are interpreting the regression slopes <strong>as comparisons of cases that differ in one predictor while being at the same levels of the other predictors</strong>.</p>
<p>As you can see, interpreting regression coefficients can be kind of tricky. The relationship between the response y and any one explanatory variable can change greatly depending on what other explanatory variables are present in the model.</p>
<p>For example, if you contrast this model with the one we run with only <em>SOUTH</em> as a predictor you will notice the intercept has changed. You cannot longer read the intercept as the mean value of homicide rate for Northern counties. <em>Adding predictors to the model changes their meaning</em>. Now the intercept index the value of homicide for southern counties that score 0 in <em>RD90</em>. In this case you have cases that meet this condition (equal zero in all your predictors), but often you may not have any case that does meet the definition of the intercept. More often than not, then, there is not much value in bothering to interpret the intercept.</p>
<p>Something you need to be particularly careful about is to interpret the coefficients in a causal manner. At least your data come from an experiment this is unlikely to be helpful. With observational data regression coefficients should not be read as indexing causal relations. This sort of textbook warning is, however, often neglectfully ignored by professional researchers. Often authors carefully draw sharp distinctions between causal and correlational claims when discussing their data analysis, but then interpret the correlational patterns in a totally causal way in their conclusion section. This is what is called the <a href="http://junkcharts.typepad.com/numbersruleyourworld/2012/07/the-causation-creep.html">causation</a> or <a href="http://www.carlislerainey.com/2012/12/05/another-example-of-causal-creep/">causal</a> creep. Beware. Don’t do this, as tempting as it may be.</p>
<p>Comparing the simple models with this more complex model we could say that adjusting for <em>SOUTH</em> does not change much the impact of <em>RD90</em> in homicide, but that adjusting for resource deprivation halves the impact of the regional effect on homicide.</p>
</div>
<div id="presenting-your-regression-results." class="section level2 hasAnchor" number="15.9">
<h2><span class="header-section-number">15.9</span> Presenting your regression results.<a href="appendix-b-regression-analysis-a-refresher.html#presenting-your-regression-results." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Communicating your results in a clear manner is incredibly important. We have seen the tabular results produced by R. If you want to use them in a paper you may need to do some tidying up of those results. There are a number of packages (<code>textreg</code>, <code>stargazer</code>) that automatise that process. They take your <code>lm</code> objects and produce tables that you can put straight away in your reports or papers. One popular trend in presenting results is the <strong>coefficient plot</strong> as an alternative to the table of regression coefficients. There are various ways of producing coefficient plots with R for a variety of models.</p>
<p>We are going to use instead the <code>plot_model()</code> function of the <code>sjPlot</code> package, that makes it easier to produce this sort of plots.</p>
<div class="sourceCode" id="cb718"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb718-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb718-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span></code></pre></div>
<p>Let’s try with a more complex example:</p>
<div class="sourceCode" id="cb719"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb719-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb719-1" aria-hidden="true" tabindex="-1"></a>fit_4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR90 <span class="sc">~</span> RD90 <span class="sc">+</span> SOUTH_f <span class="sc">+</span> DV90 <span class="sc">+</span> MA90 <span class="sc">+</span> PS90, <span class="at">data=</span>ncovr)</span>
<span id="cb719-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb719-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(fit_4, <span class="at">breakLabelsAt =</span> <span class="dv">30</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-439"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-439-1.png" alt="A plot of points with horizontal line segments attached to them, over a grey grid. The vertical axis has labels such as 'PS90', 'MA90', 'RD90' and so on, while the horizontal axis ranges from negative one to four. One point to the left of zero appears as red, while the others to the right are blue. One horizontal line segment runs through each point, matching their colour." width="672" />
<p class="caption">
FIGURE 15.8: Regression forest plot for the results of a regression
</p>
</div>
<p>What you see plotted here is the point estimates (the circles), the confidence intervals around those estimates (the longer the line the less precise the estimate), and the colours represent whether the effect is negative (red) or positive (blue). There are other packages that also provide similar functionality, like the <code>dotwhisker</code> package that you may want to explore.</p>
<p>The <code>sjPlot</code> package also allows you to produce html tables for more professional presentation of your regression tables. For this we use the <code>tab_model()</code> function.</p>
<div class="sourceCode" id="cb720"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb720-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb720-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(fit_4)</span></code></pre></div>
<p>You can customise this table. For example, you can change the name that is displayed for the dependent variable with the <code>dv.labels =</code> parameter, and you could change the labels for the independent variables with the <code>pred.labels =</code> parameter.</p>
<div class="sourceCode" id="cb721"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb721-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb721-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(fit_4, </span>
<span id="cb721-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb721-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">dv.labels =</span> <span class="st">&quot;Homicide rate 1990&quot;</span>, </span>
<span id="cb721-3"><a href="appendix-b-regression-analysis-a-refresher.html#cb721-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">pred.labels =</span> <span class="fu">c</span>(<span class="st">&quot;(Intercept)&quot;</span>, <span class="st">&quot;Resource deprivation&quot;</span>,<span class="st">&quot;South&quot;</span>, </span>
<span id="cb721-4"><a href="appendix-b-regression-analysis-a-refresher.html#cb721-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">&quot;Percent divorced males&quot;</span>, <span class="st">&quot;Median age&quot;</span>,<span class="st">&quot;Population structure&quot;</span>))</span></code></pre></div>
<p>The <code>tab_model()</code> function is great if you have a html output. In case you’re making your tables for a PDF output, you might want to consider the <code>stargazer</code> package, from which the function <code>stargazer()</code> stargazer command produces LaTeX code, HTML code and ASCII text for well-formatted tables.</p>
<div class="sourceCode" id="cb722"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb722-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb722-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code></pre></div>
<div class="sourceCode" id="cb723"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb723-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb723-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(fit_4)</span></code></pre></div>
% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Thu, Sep 08, 2022 - 15:40:47
<p>You could also use this to show the results of several models side by side.</p>
<div class="sourceCode" id="cb724"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb724-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb724-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(fit_3, fit_4)</span></code></pre></div>
% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Thu, Sep 08, 2022 - 15:40:47
<p>Besides tables, visual display of the effects of the variables in the model are particularly helpful. The <code>effects</code> package allows us to produce plots to visualise these relationships (when adjusting for the other variables in the model). Here’s an example going back to our model fit_3 which contained <em>SOUTH</em> and <em>RD90</em> predictor variables:</p>
<div class="sourceCode" id="cb725"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb725-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb725-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb725-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb725-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(fit_3), <span class="at">ask=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-443"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-443-1.png" alt="Two line plots side by side, the first titled 'RD90 effect plot', and the second 'South f effect plot'. Both have a vertical axis labeled 'HR90', though their values differ. The left plot has horizontal axis 'RD90' from negative two to six, while the right is 'South f' from zero to one. The lines are of similar slope, but not identical. The line in the left plot has a shaded light blue area around it, which grows as you move away from zero. The line on the right ends in small circles at zero and one, which both lie on pink error bars." width="672" />
<p class="caption">
FIGURE 15.9: Effect plots for a regression
</p>
</div>
<p>Notice that the line has a confidence interval drawn around it and that the predicted means for southern and northern counties (when controlling for <em>RD90</em>) also have a confidence interval.</p>
</div>
<div id="rescaling-input-variables-to-assist-interpretation" class="section level2 hasAnchor" number="15.10">
<h2><span class="header-section-number">15.10</span> Rescaling input variables to assist interpretation<a href="appendix-b-regression-analysis-a-refresher.html#rescaling-input-variables-to-assist-interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The interpretation or regression coefficients is sensitive to the scale of measurement of the predictors. This means one cannot compare the magnitude of the coefficients to compare the relevance of variables to predict the response variable. Let’s look at the more recent model, how can we tell what predictors have a stronger effect?</p>
<div class="sourceCode" id="cb726"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb726-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb726-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_4)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90 + SOUTH_f + DV90 + MA90 + PS90, data = ncovr)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -15.74  -2.59  -0.68   1.71  69.18 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   4.2035     0.9847    4.27    2e-05 ***
## RD90          3.1992     0.1117   28.65   &lt;2e-16 ***
## SOUTH_f1      2.5998     0.2156   12.06   &lt;2e-16 ***
## DV90          0.4759     0.0531    8.97   &lt;2e-16 ***
## MA90         -0.0761     0.0274   -2.77   0.0056 ** 
## PS90          1.2645     0.1005   12.59   &lt;2e-16 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.04 on 3079 degrees of freedom
## Multiple R-squared:  0.426,  Adjusted R-squared:  0.425 
## F-statistic:  457 on 5 and 3079 DF,  p-value: &lt;2e-16</code></pre>
<p>We just cannot. One way of dealing with this is by rescaling the input variables. A common method involves subtracting the mean and dividing by the standard deviation of each numerical input. The coefficients in these models is the expected difference in the response variable, comparing units that differ by one standard deviation in the predictor while adjusting for other predictors in the model.</p>
<p>Instead, <span class="citation">Gelman (<a href="#ref-Gelman_2008" role="doc-biblioref">2008</a>)</span> has proposed dividing each numeric variables <em>by two times its standard deviation</em>, so that the generic comparison is with inputs equal to plus/minus one standard deviation. As Gelman explains the resulting coefficients are then comparable to untransformed binary predictors. The implementation of this approach in the <code>arm</code> package subtract the mean of each binary input while it subtract the mean and divide by two standard deviations for every numeric input.</p>
<p>The way we would obtain these rescaled inputs uses the <code>standardize()</code> function of the <code>arm</code> package, that takes as an argument the name of the stored fit model.</p>
<div class="sourceCode" id="cb728"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb728-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb728-1" aria-hidden="true" tabindex="-1"></a>arm<span class="sc">::</span><span class="fu">standardize</span>(fit_4)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ z.RD90 + c.SOUTH_f + z.DV90 + z.MA90 + z.PS90, 
##     data = ncovr)
## 
## Coefficients:
## (Intercept)       z.RD90    c.SOUTH_f       z.DV90  
##       6.183        6.398        2.600        1.650  
##      z.MA90       z.PS90  
##      -0.548        2.529</code></pre>
<p>Notice the main change affects the numerical predictors. The unstandardised coefficients are influenced by the degree of variability in your predictors, which means that typically they will be larger for your binary inputs. With unstandardised coefficients you are comparing complete change in one variable (whether one is a Southern county or not) with one-unit changes in your numerical variable, which may not amount to much change. So, by putting in a comparable scale, you avoid this problem.</p>
<p>Standardising in the way described here will help you to make fairer comparisons. This standardised coefficients are comparable in a way that the unstandardised coefficients are not. We can now see what inputs have a comparatively stronger effect. It is very important to realise, though, that one <strong>should not</strong> compare standardised coefficients <em>across different models</em>.</p>
</div>
<div id="testing-conditional-hypothesis-interactions" class="section level2 hasAnchor" number="15.11">
<h2><span class="header-section-number">15.11</span> Testing conditional hypothesis: interactions<a href="appendix-b-regression-analysis-a-refresher.html#testing-conditional-hypothesis-interactions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the social sciences there is a great interest in what are called conditional hypothesis or interactions. Many of our theories do not assume simply <strong>additive effects</strong> but <strong>multiplicative effects</strong>.For example, <span class="citation">Wikström, Tseloni, and Karlis (<a href="#ref-Wikstrom_2011" role="doc-biblioref">2011</a>)</span> suggest that the threat of punishment only affects the probability of involvement on crime for those that have a propensity to offend but are largely irrelevant for people who do not have this propensity. Or you may think that a particular crime prevention programme may work in some environments but not in others. The interest in this kind of conditional hypothesis is growing.</p>
<p>One of the assumptions of the regression model is that the relationship between the response variable and your predictors is additive. That is, if you have two predictors <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>. Regression assumes that the effect of <span class="math inline">\(x_1\)</span> on <code>y</code> is the same at all levels of <span class="math inline">\(x_2\)</span>. If that is not the case, you are then violating one of the assumptions of regression. This is in fact one of the most important assumptions of regression, even if researchers often overlook it.</p>
<p>One way of extending our model to accommodate for interaction effects is to add additional terms to our model, a third predictor <span class="math inline">\(x_3\)</span>, where <span class="math inline">\(x_3\)</span> is simply the product of multiplying <span class="math inline">\(x_1\)</span> by <span class="math inline">\(x_2\)</span>. Notice we keep a term for each of the <strong>main effects</strong> (the original predictors) as well as a new term for the interaction effect. “Analysts should include all constitutive terms when specifying multiplicative interaction models except in very rare circumstances” <span class="citation">Brambor, Clark, and Golder (<a href="#ref-Brambor_2006" role="doc-biblioref">2006</a>)</span> p.66).</p>
<p>How do we do this in R? One way is to use the following notation in the formula argument. Notice how we have added a third term <code>RD90:SOUTH_f</code>, which is asking R to test the conditional hypothesis that resource deprivation may have a different impact on homicide for southern and northern counties.</p>
<div class="sourceCode" id="cb730"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb730-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb730-1" aria-hidden="true" tabindex="-1"></a>fit_5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR90 <span class="sc">~</span> RD90 <span class="sc">+</span> SOUTH_f <span class="sc">+</span> RD90<span class="sc">:</span>SOUTH_f , <span class="at">data=</span>ncovr)</span>
<span id="cb730-2"><a href="appendix-b-regression-analysis-a-refresher.html#cb730-2" aria-hidden="true" tabindex="-1"></a><span class="co"># which is equivalent to: </span></span>
<span id="cb730-3"><a href="appendix-b-regression-analysis-a-refresher.html#cb730-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fit_5 &lt;- lm(HR90 ~ RD90 * SOUTH_f , data=ncovr)</span></span>
<span id="cb730-4"><a href="appendix-b-regression-analysis-a-refresher.html#cb730-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90 + SOUTH_f + RD90:SOUTH_f, data = ncovr)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -17.05  -3.00  -0.57   2.23  68.14 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      4.548      0.159   28.68   &lt;2e-16 ***
## RD90             2.581      0.196   13.15   &lt;2e-16 ***
## SOUTH_f1         3.261      0.225   14.51   &lt;2e-16 ***
## RD90:SOUTH_f1    0.562      0.238    2.37    0.018 *  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.29 on 3081 degrees of freedom
## Multiple R-squared:  0.366,  Adjusted R-squared:  0.365 
## F-statistic:  592 on 3 and 3081 DF,  p-value: &lt;2e-16</code></pre>
<p>You see here that essentially you have only two inputs (resource deprivation and south) but several regression coefficients. Gelman and Hill (2007) suggest reserving the term input for the variables encoding the information and to use the term predictor to refer to each of the terms in the model. So here we have two inputs and three predictors (one for SOUTH, another for resource deprivation, and a final one for the interaction effect).</p>
<p>In this case the test for the interaction effect is significant, which suggests there is such an interaction. Let’s visualise the results with the <code>effects</code> package:</p>
<div class="sourceCode" id="cb732"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb732-1"><a href="appendix-b-regression-analysis-a-refresher.html#cb732-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(fit_5), <span class="at">ask=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-447"></span>
<img src="crime_mapping_files/figure-html/unnamed-chunk-447-1.png" alt="Two line plots with the same axes, with similar straight blue lines in each that have light blue shaded areas around them which grows away from zero. The first is titled 'South f equals zero', and the second 'South f equals one'. The vertical axis is 'HR90', and the horizontal axis 'RD90'. The slope of the second line is slightly higher, and it also has a smaller shaded blue area." width="672" />
<p class="caption">
FIGURE 15.10: Effect plots for regression testing conditional hypothesis
</p>
</div>
<p>Notice that essentially what we are doing is running two regression lines and testing whether the slope is different for the two groups. The intercept is different, we know that Southern counties are more violent, but what we are testing here is whether the level of homicide goes up in a steeper fashion (and in the same direction) for one or the other group as the level of resource deprivation goes up. We see that’s the case here. The estimated lines are almost parallel, but the slope is a bit more steep in the Southern counties. In southern counties resource deprivation seems to have more of an impact on homicide than in northern counties.</p>
<p>A word of warning, the moment you introduce an interaction effect the meaning of the coefficients for the other predictors changes (what it is often referred as to the “main effects” as opposed to the interaction effect). You cannot retain the interpretation we introduced earlier. Now, for example, the coefficient for the <code>SOUTH</code> variable relates the marginal effect of this variable when <code>RD90</code> equals zero. The typical table of results helps you to understand whether the effects are significant but offers little of interest that will help you to meaningfully interpret what the effects are. For this is better you use some of the graphical displays we have covered.</p>
<p>Essentially what happens is that the regression coefficients that get printed are interpretable only for certain groups. So now:</p>
<ul>
<li><p>The intercept still represents the predicted score of homicide for southern counties and have a score of 0 in resource deprivation (as before).</p></li>
<li><p>The coefficient of <em>SOUTH_f1</em> now can be thought of as the difference between the predicted score of homicide rate for northern counties <em>that have a score of 0 in resource deprivation</em> and northern counties <em>that have a score of 0 in resource deprivation</em>.</p></li>
<li><p>The coefficient of <em>RD90</em> now becomes the comparison of mean homicide rate <em>for southern</em> counties who differ by one point in resource deprivation.</p></li>
<li><p>The coefficient for the interaction term represents the difference in the slope for <em>RD90</em> comparing southern and northern counties, the difference in the slope of the two lines that we visualised above.</p></li>
</ul>
</div>
<div id="model-building-and-variable-selection" class="section level2 hasAnchor" number="15.12">
<h2><span class="header-section-number">15.12</span> Model building and variable selection<a href="appendix-b-regression-analysis-a-refresher.html#model-building-and-variable-selection" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How do you construct a good model? This partly depends on your goal, although there are commonalities. You do want to start with theory as a way to select your predictors and when specifying the nature of the relationship to your response variable (e.g., additive, multiplicative). Gelman and Hill (2007) provide a series of general principles. I would like to emphasise at this stage two of them:</p>
<ul>
<li><p>Include all input variables that, for substantive reasons, might be expected to be important in predicting the outcome.</p></li>
<li><p>For inputs with large effects, consider including their interactions as well.</p></li>
</ul>
<p>It is often the case that for any model, the response variable is only related to a subset of the predictors. There are some scenarios where you may be interested in understanding what is the best subset of predictors. Imagine that you want to develop a risk assessment tool to be used by police officers that respond to a domestic violence incident, so that you could use this tool for forecasting the future risk of violence. There is a cost to adding too many predictors. A police officer’s time should not be wasted gathering information on predictors that are not associated with future risk. So you may want to identify the predictors that will help in this process.</p>
<p>Ideally, we would like to perform variable selection by trying out a lot of different models, each containing a different subset of the predictors. There are various statistics that help in making comparisons across models. Unfortunately, as the number of potentially relevant predictors increases the number of potential models to compare increases exponentially. So you need methods that help you in this process. There are a number of tools that you can use for <strong>variable selection</strong> but this goes beyond the aims of this introduction. If you are interested you may want to read <a href="http://link.springer.com/chapter/10.1007/978-1-4614-7138-7_6">this</a>.</p>
</div>
<div id="regression-assumptions" class="section level2 hasAnchor" number="15.13">
<h2><span class="header-section-number">15.13</span> Regression assumptions<a href="appendix-b-regression-analysis-a-refresher.html#regression-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Although so far we have discussed the practicalities of fitting and interpreting regression models, in practical applications you want to first check your model and proceed from there. There is not much point spending time interpreting your model until you know that the model reasonably fits your data.</p>
<p>In previous data analysis modules we surely covered assumptions made by various statistical tests. The regression model also makes assumptions of its own. In fact, there are so many that we could spend an entire class discussing them. Gelman and Hill (2007) point out that the most important regression assumptions by decreasing order of importance are:</p>
<ul>
<li><strong>Validity</strong>. The data should be appropriate for the question that you are trying to answer:</li>
</ul>
<blockquote>
<p>“Optimally, this means that the outcome measure should accurately reflect the phenomenon of interest, the model should include all relevant predictors, and the model should generalize to all cases to which it will be applied… Data used in empirical research rarely meet all (if any) of these criteria precisely. However, keeping these goals in mind can help you be precise about the types of questions you can and cannot answer reliably”</p>
</blockquote>
<ul>
<li><p><strong>Additiviy and linearity</strong>. These are the most important mathematical assumptions of the model. We already talked about additivity in previous sessions and discussed how you can include interaction effects in your models if the additivity assumption is violated. We will discuss problems with non-linearities today as well as ways to diagnose and solve this problem. If the relationship is non linear (e.g, it is curvilinear) predicted values will be wrong in a biased manner, meaning that predicted values will systematically miss the true pattern of the mean of y (as related to the x-variables).</p></li>
<li><p><strong>Independence of errors</strong>. Regression assumes that the errors from the prediction line (or hyperplane) are independent. If there is dependency between the observations (you are assessing change across the same units, working with spatial units, or with units that are somehow grouped such as students from the same class), you may have to use models that are more appropriate (e.g., multilevel models, spatial regression, etc.).</p></li>
<li><p><strong>Equal variances of errors</strong>. When the variance of the residuals is unequal, you may need different estimation methods. This is, nonetheless, considered a minor issue. There is a small effect on the validity of t-test and F-test results, but generally regression inferences are robust with regard to the variance issue.</p></li>
<li><p><strong>Normality of errors</strong>. The residuals should be normally distributed. Gelman and Hill (2007: 46) discuss this as the least important of the assumptions and in fact “do <em>not</em> recommend diagnostics of the normality of the regression residuals”. If the errors do not have a normal distribution, it usually is not particularly serious. Regression inferences tend to be robust with respect to normality (or nonnormality of the errors). In practice, the residuals may appear to be nonnormal when the wrong regression equation has been used. So, I will show you how to inspect normality of the residuals not because this is a problem on itself, but because it may be give you further evidence that there is some other problem with the model you are applying to your data.</p></li>
</ul>
<p>Apart from this, it is convenient to diagnose multicollinearity (this affects interpretation) and influential observations.</p>
<p>So these are the assumptions of linear regression, and today we will go through how to test for them, and also what are some options that you can consider if you find that your model violates them. While finding that some of the assumptions are violated do not necessarily mean that you have to scrap your model, it is important to use these diagnostics to illustrate that you have considered what the possible issues with your model is, and if you find any serious issues that you address them.</p>
<p>You may have noticed the second of this assumption is independence of errors. This is an issue with spatial data. If you have spatial autocorrelation basically you are saying that your observations are not independent. What happens in area X is likely to be similar to what happens in its surrounding neighbours (if you have positive spatial autocorrelation). What do you do? Well, that’s what we will cover next week. We will learn how to fit regression models where you have spatial dependency.</p>
</div>
<div id="summary-and-further-reading-11" class="section level2 hasAnchor" number="15.14">
<h2><span class="header-section-number">15.14</span> Summary and further reading<a href="appendix-b-regression-analysis-a-refresher.html#summary-and-further-reading-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><span class="citation">Friedman, Hastie, and Tibshirani (<a href="#ref-Friedman_2001" role="doc-biblioref">2001</a>)</span> is a classic book for anyone looking to develop their skills modelling data with comprehensive examples and exercises to follow in R.</p>
<p>Models with interaction terms are too often misinterpreted. We strongly recommend a read of <span class="citation">Brambor, Clark, and Golder (<a href="#ref-Brambor_2006" role="doc-biblioref">2006</a>)</span> to facilitate correct interpretation. Equally, <span class="citation">Fox (<a href="#ref-Fox_2003" role="doc-biblioref">2003</a>)</span> piece on the <code>effects</code> package goes to great detail to explain the logic and some of the options that are available when producing plots to show interactions with this package.</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Baller_2001" class="csl-entry">
Baller, Robert, Luc Anselin, Steven Messner, Glenn Deane, and Darnell Hawkins. 2001. <span>“Structural Covariates of US County Homicide Rates: Incorporating Spatial Effects.”</span> <em>Criminology</em> 39 (3): 561–88.
</div>
<div id="ref-Brambor_2006" class="csl-entry">
Brambor, Thomas, William Clark, and Matt Golder. 2006. <span>“Understanding Interaction Models: Improving Empirical Analyses.”</span> <em>Political Analysis</em> 14 (1): 63–82.
</div>
<div id="ref-Fox_2003" class="csl-entry">
Fox, John. 2003. <span>“Effect Displays in r for Generalised Linear Models.”</span> <em>Journal of Statistical Software</em> 8 (15).
</div>
<div id="ref-Friedman_2001" class="csl-entry">
Friedman, Jerome, Trevor Hastie, and Robert Tibshirani. 2001. <em>The Elements of Statistical Learning</em>. Vol. 1. 10. Springer series in statistics New York.
</div>
<div id="ref-Gelman_2008" class="csl-entry">
Gelman, Andrew. 2008. <span>“Scaling Regression Inputs by Dividing by Two Standard Deviations.”</span> <em>Statistics in Medicine</em> 27: 2865–73.
</div>
<div id="ref-Gelman_2007" class="csl-entry">
Gelman, Andrew, and Jenniffer Hill. 2007. <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge: Cambridge University Press.
</div>
<div id="ref-James_2013" class="csl-entry">
James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2013. <em>An Introduction to Statistical Learning with Applications in r</em>. New York: Springer.
</div>
<div id="ref-Sampson_1997" class="csl-entry">
Sampson, Robert, Stephen Raudenbush, and Felton Earls. 1997. <span>“Neighborhoods and Violent Crime: A Multilevel Study of Collective Efficacy.”</span> <em>Science</em> 277 (5328): 918–24.
</div>
<div id="ref-DeVeaux_2012" class="csl-entry">
Veaux, RD De, PF Velleman, and DE Bock. 2012. <em>Stats: Data and Models with Statistical Methods for the Social Sciences</em>. Boston, MA: Pearson.
</div>
<div id="ref-Weisburd_2014" class="csl-entry">
Weisburd, David, and Chester Britt. 2014. <em>Statistics in Criminal Justice</em>. Springer.
</div>
<div id="ref-Wikstrom_2011" class="csl-entry">
Wikström, Per-Olof, Andromachi Tseloni, and Dimitris Karlis. 2011. <span>“Do People Comply with the Law Because They Fear Getting Caught?”</span> <em>European Journal of Criminology</em> 8 (5): 401–20.
</div>
<div id="ref-Wilson_1982" class="csl-entry">
Wilson, James, and George Kelling. 1982. <span>“Broken Windows.”</span> <em>Atlantic Monthly</em> 249 (3): 29–38.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="appendix-a-quick-intro-to-r-and-rstudio.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix-c-sourcing-geographical-data-for-crime-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/14-appendix_b_regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["crime_mapping.pdf", "crime_mapping.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
